const { buildOptions } = require('./build-options');

// Curated list of widely-recognized albums spanning genres and decades, used as the
// fixed option set for the "Favorite Album of All Time" poll. Voters pick from this
// list rather than typing free text, so results stay clean and comparable.
// Tuples are [artist, title, year].
const RAW_ALBUMS = [
  ['The Beatles', 'Abbey Road', 1969],
  ["The Beatles", "Sgt. Pepper's Lonely Hearts Club Band", 1967],
  ['The Beatles', 'Revolver', 1966],
  ['The Beatles', 'The Beatles (White Album)', 1968],
  ['The Beatles', 'Rubber Soul', 1965],
  ['Pink Floyd', 'The Dark Side of the Moon', 1973],
  ['Pink Floyd', 'Wish You Were Here', 1975],
  ['Pink Floyd', 'The Wall', 1979],
  ['Pink Floyd', 'Animals', 1977],
  ['Led Zeppelin', 'Led Zeppelin IV', 1971],
  ['Led Zeppelin', 'Physical Graffiti', 1975],
  ['Led Zeppelin', 'Led Zeppelin II', 1969],
  ['The Rolling Stones', 'Exile on Main St.', 1972],
  ['The Rolling Stones', 'Let It Bleed', 1969],
  ['The Rolling Stones', 'Sticky Fingers', 1971],
  ['The Beach Boys', 'Pet Sounds', 1966],
  ['Bob Dylan', 'Blood on the Tracks', 1975],
  ['Bob Dylan', 'Highway 61 Revisited', 1965],
  ['Bob Dylan', 'Blonde on Blonde', 1966],
  ['Fleetwood Mac', 'Rumours', 1977],
  ['The Who', "Who's Next", 1971],
  ['Carole King', 'Tapestry', 1971],
  ['Marvin Gaye', "What's Going On", 1971],
  ['Stevie Wonder', 'Songs in the Key of Life', 1976],
  ['Stevie Wonder', 'Innervisions', 1973],
  ['David Bowie', 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 1972],
  ['David Bowie', 'Hunky Dory', 1971],
  ['David Bowie', 'Low', 1977],
  ['Joni Mitchell', 'Blue', 1971],
  ['Simon & Garfunkel', 'Bridge over Troubled Water', 1970],
  ['Van Morrison', 'Astral Weeks', 1968],
  ['The Velvet Underground', 'The Velvet Underground & Nico', 1967],
  ['Creedence Clearwater Revival', "Cosmo's Factory", 1970],
  ['Neil Young', 'Harvest', 1972],
  ['Neil Young', 'After the Gold Rush', 1970],
  ['The Clash', 'London Calling', 1979],
  ['Patti Smith', 'Horses', 1975],
  ['Talking Heads', 'Remain in Light', 1980],
  ['Talking Heads', 'Speaking in Tongues', 1983],
  ['Elton John', 'Goodbye Yellow Brick Road', 1973],
  ['Steely Dan', 'Aja', 1977],
  ['Eagles', 'Hotel California', 1976],
  ['Bruce Springsteen', 'Born to Run', 1975],
  ['Bruce Springsteen', 'Born in the U.S.A.', 1984],
  ['Bruce Springsteen', 'Darkness on the Edge of Town', 1978],
  ['Queen', 'A Night at the Opera', 1975],
  ['Aretha Franklin', 'I Never Loved a Man the Way I Love You', 1967],
  ['Sly and the Family Stone', "There's a Riot Goin' On", 1971],
  ['The Band', 'Music from Big Pink', 1968],
  ['James Brown', 'Live at the Apollo', 1963],
  ['Al Green', "Call Me", 1973],
  ['Michael Jackson', 'Thriller', 1982],
  ['Michael Jackson', 'Off the Wall', 1979],
  ['Michael Jackson', 'Bad', 1987],
  ['Prince', 'Purple Rain', 1984],
  ['Prince', 'Sign o’ the Times', 1987],
  ['Prince', '1999', 1982],
  ['Madonna', 'Like a Prayer', 1989],
  ['U2', 'The Joshua Tree', 1987],
  ['U2', 'Achtung Baby', 1991],
  ['R.E.M.', 'Automatic for the People', 1992],
  ['Metallica', 'Master of Puppets', 1986],
  ['Metallica', 'Ride the Lightning', 1984],
  ['Metallica', 'Metallica (The Black Album)', 1991],
  ['Guns N’ Roses', 'Appetite for Destruction', 1987],
  ['Run-DMC', 'Raising Hell', 1986],
  ['Public Enemy', 'It Takes a Nation of Millions to Hold Us Back', 1988],
  ['The Smiths', 'The Queen Is Dead', 1986],
  ['New Order', 'Power, Corruption & Lies', 1983],
  ['Depeche Mode', 'Violator', 1990],
  ['Kate Bush', 'Hounds of Love', 1985],
  ['Def Leppard', 'Hysteria', 1987],
  ['AC/DC', 'Back in Black', 1980],
  ['Iron Maiden', 'The Number of the Beast', 1982],
  ['Whitney Houston', 'Whitney Houston', 1985],
  ['Tracy Chapman', 'Tracy Chapman', 1988],
  ['Nirvana', 'Nevermind', 1991],
  ['Nirvana', 'In Utero', 1993],
  ['Pearl Jam', 'Ten', 1991],
  ['Radiohead', 'OK Computer', 1997],
  ['Radiohead', 'The Bends', 1995],
  ['Radiohead', 'Kid A', 2000],
  ['Radiohead', 'In Rainbows', 2007],
  ['My Bloody Valentine', 'Loveless', 1991],
  ['Pixies', 'Doolittle', 1989],
  ['Beastie Boys', "Paul's Boutique", 1989],
  ['Beastie Boys', 'Ill Communication', 1994],
  ['Wu-Tang Clan', 'Enter the Wu-Tang (36 Chambers)', 1993],
  ['Nas', 'Illmatic', 1994],
  ['The Notorious B.I.G.', 'Ready to Die', 1994],
  ['2Pac', 'All Eyez on Me', 1996],
  ['Dr. Dre', 'The Chronic', 1992],
  ['Snoop Dogg', 'Doggystyle', 1993],
  ['A Tribe Called Quest', 'The Low End Theory', 1991],
  ['Portishead', 'Dummy', 1994],
  ['Massive Attack', 'Blue Lines', 1991],
  ['Massive Attack', 'Mezzanine', 1998],
  ['Björk', 'Homogenic', 1997],
  ['Alanis Morissette', 'Jagged Little Pill', 1995],
  ['Oasis', 'Definitely Maybe', 1994],
  ['Oasis', "(What's the Story) Morning Glory?", 1995],
  ['Blur', 'Parklife', 1994],
  ['Weezer', 'Weezer (The Blue Album)', 1994],
  ['Green Day', 'Dookie', 1994],
  ['Smashing Pumpkins', 'Mellon Collie and the Infinite Sadness', 1995],
  ['Smashing Pumpkins', 'Siamese Dream', 1993],
  ['Soundgarden', 'Superunknown', 1994],
  ['Alice in Chains', 'Dirt', 1992],
  ['Rage Against the Machine', 'Rage Against the Machine', 1992],
  ['Foo Fighters', 'The Colour and the Shape', 1997],
  ['Jeff Buckley', 'Grace', 1994],
  ['PJ Harvey', 'To Bring You My Love', 1995],
  ['Fiona Apple', 'Tidal', 1996],
  ['Lauryn Hill', 'The Miseducation of Lauryn Hill', 1998],
  ["D'Angelo", 'Voodoo', 2000],
  ['OutKast', 'Aquemini', 1998],
  ['OutKast', 'Stankonia', 2000],
  ['Daft Punk', 'Homework', 1997],
  ['Daft Punk', 'Discovery', 2001],
  ['Daft Punk', 'Random Access Memories', 2013],
  ['The Prodigy', 'The Fat of the Land', 1997],
  ['Aphex Twin', 'Selected Ambient Works 85-92', 1992],
  ['The Strokes', 'Is This It', 2001],
  ['The White Stripes', 'Elephant', 2003],
  ['Arcade Fire', 'Funeral', 2004],
  ['Kanye West', 'The College Dropout', 2004],
  ['Kanye West', 'Late Registration', 2005],
  ['Kanye West', 'My Beautiful Dark Twisted Fantasy', 2010],
  ['Kanye West', 'Yeezus', 2013],
  ['Jay-Z', 'The Blueprint', 2001],
  ['Jay-Z', 'The Black Album', 2003],
  ['Eminem', 'The Marshall Mathers LP', 2000],
  ['Interpol', 'Turn on the Bright Lights', 2002],
  ['Yeah Yeah Yeahs', 'Fever to Tell', 2003],
  ['LCD Soundsystem', 'Sound of Silver', 2007],
  ['Amy Winehouse', 'Back to Black', 2006],
  ['Gorillaz', 'Demon Days', 2005],
  ['Modest Mouse', 'The Moon & Antarctica', 2000],
  ['Sufjan Stevens', 'Illinois', 2005],
  ['Bon Iver', 'For Emma, Forever Ago', 2007],
  ['Bon Iver', 'Bon Iver, Bon Iver', 2011],
  ['Vampire Weekend', 'Vampire Weekend', 2008],
  ['Vampire Weekend', 'Modern Vampires of the City', 2013],
  ['MGMT', 'Oracular Spectacular', 2007],
  ['Death Cab for Cutie', 'Transatlanticism', 2003],
  ['My Chemical Romance', 'The Black Parade', 2006],
  ['Fleet Foxes', 'Fleet Foxes', 2008],
  ['Lorde', 'Pure Heroine', 2013],
  ['Kendrick Lamar', 'good kid, m.A.A.d city', 2012],
  ['Kendrick Lamar', 'To Pimp a Butterfly', 2015],
  ['Kendrick Lamar', 'DAMN.', 2017],
  ['Kendrick Lamar', 'Mr. Morale & the Big Steppers', 2022],
  ['Frank Ocean', 'channel ORANGE', 2012],
  ['Frank Ocean', 'Blonde', 2016],
  ['Beyoncé', 'Lemonade', 2016],
  ['Beyoncé', 'Beyoncé', 2013],
  ['Beyoncé', 'Renaissance', 2022],
  ['Taylor Swift', '1989', 2014],
  ['Taylor Swift', 'Red', 2012],
  ['Taylor Swift', 'folklore', 2020],
  ['Adele', '21', 2011],
  ['Adele', '25', 2015],
  ['Arctic Monkeys', 'AM', 2013],
  ['Tame Impala', 'Currents', 2015],
  ['The War on Drugs', 'Lost in the Dream', 2014],
  ['Chance the Rapper', 'Coloring Book', 2016],
  ['Drake', 'Take Care', 2011],
  ['Billie Eilish', 'When We All Fall Asleep, Where Do We Go?', 2019],
  ['SZA', 'Ctrl', 2017],
  ['SZA', 'SOS', 2022],
  ['Solange', 'A Seat at the Table', 2016],
  ['Childish Gambino', 'Because the Internet', 2013],
  ['Mac Miller', 'Swimming', 2018],
  ['Travis Scott', 'Astroworld', 2018],
  ['Phoebe Bridgers', 'Punisher', 2020],
  ['Harry Styles', 'Fine Line', 2019],
  ['Olivia Rodrigo', 'SOUR', 2021],
  ['boygenius', 'the record', 2023],
  ['Bad Bunny', 'Un Verano Sin Ti', 2022],
  ['Miles Davis', 'Kind of Blue', 1959],
  ['John Coltrane', 'A Love Supreme', 1965],
  ['Dave Brubeck', 'Time Out', 1959],
  ['Nina Simone', 'I Put a Spell on You', 1965],
  ['Johnny Cash', 'At Folsom Prison', 1968],
  ['Willie Nelson', 'Red Headed Stranger', 1975],
  ['Dolly Parton', 'Coat of Many Colors', 1971],
  ['ABBA', 'Arrival', 1976],
  ['Fela Kuti', 'Zombie', 1976],
  ['Bob Marley & The Wailers', 'Exodus', 1977],
  ['Bob Marley & The Wailers', 'Legend', 1984],
  ['The Cure', 'Disintegration', 1989],
  ['Sonic Youth', 'Daydream Nation', 1988],
  ['Slint', 'Spiderland', 1991],
  ['Kraftwerk', 'Trans-Europe Express', 1977],
  ['Brian Eno', 'Another Green World', 1975],
  ['King Crimson', 'In the Court of the Crimson King', 1969],
  ['Yes', 'Close to the Edge', 1972],
  ['Genesis', 'Selling England by the Pound', 1973],
  ['Rush', 'Moving Pictures', 1981],
  ['Black Sabbath', 'Paranoid', 1970],
  ['Judas Priest', 'British Steel', 1980],
  ['Slayer', 'Reign in Blood', 1986],
  ['Pantera', 'Vulgar Display of Power', 1992],
  ['Nine Inch Nails', 'The Downward Spiral', 1994],
  ['Tool', 'Lateralus', 2001],
  ['System of a Down', 'Toxicity', 2001],
];

module.exports = buildOptions(RAW_ALBUMS);
