const { buildOptions } = require('./build-options');

// Curated list of widely-recognized albums spanning genres and decades, used as the
// fixed option set for the "Favorite Album of All Time" poll. Voters pick from this
// list rather than typing free text, so results stay clean and comparable.
// Tuples are [artist, title, year].
const RAW_ALBUMS = [
  ['The Beatles', 'Abbey Road', 1969],
  ["The Beatles", "Sgt. Pepper's Lonely Hearts Club Band", 1967],
  ['The Beatles', 'Revolver', 1966],
  ['The Beatles', 'The Beatles (White Album)', 1968],
  ['The Beatles', 'Rubber Soul', 1965],
  ['Pink Floyd', 'The Dark Side of the Moon', 1973],
  ['Pink Floyd', 'Wish You Were Here', 1975],
  ['Pink Floyd', 'The Wall', 1979],
  ['Pink Floyd', 'Animals', 1977],
  ['Led Zeppelin', 'Led Zeppelin IV', 1971],
  ['Led Zeppelin', 'Physical Graffiti', 1975],
  ['Led Zeppelin', 'Led Zeppelin II', 1969],
  ['The Rolling Stones', 'Exile on Main St.', 1972],
  ['The Rolling Stones', 'Let It Bleed', 1969],
  ['The Rolling Stones', 'Sticky Fingers', 1971],
  ['The Beach Boys', 'Pet Sounds', 1966],
  ['Bob Dylan', 'Blood on the Tracks', 1975],
  ['Bob Dylan', 'Highway 61 Revisited', 1965],
  ['Bob Dylan', 'Blonde on Blonde', 1966],
  ['Fleetwood Mac', 'Rumours', 1977],
  ['The Who', "Who's Next", 1971],
  ['Carole King', 'Tapestry', 1971],
  ['Marvin Gaye', "What's Going On", 1971],
  ['Stevie Wonder', 'Songs in the Key of Life', 1976],
  ['Stevie Wonder', 'Innervisions', 1973],
  ['David Bowie', 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 1972],
  ['David Bowie', 'Hunky Dory', 1971],
  ['David Bowie', 'Low', 1977],
  ['Joni Mitchell', 'Blue', 1971],
  ['Simon & Garfunkel', 'Bridge over Troubled Water', 1970],
  ['Van Morrison', 'Astral Weeks', 1968],
  ['The Velvet Underground', 'The Velvet Underground & Nico', 1967],
  ['Creedence Clearwater Revival', "Cosmo's Factory", 1970],
  ['Neil Young', 'Harvest', 1972],
  ['Neil Young', 'After the Gold Rush', 1970],
  ['The Clash', 'London Calling', 1979],
  ['Patti Smith', 'Horses', 1975],
  ['Talking Heads', 'Remain in Light', 1980],
  ['Talking Heads', 'Speaking in Tongues', 1983],
  ['Elton John', 'Goodbye Yellow Brick Road', 1973],
  ['Steely Dan', 'Aja', 1977],
  ['Eagles', 'Hotel California', 1976],
  ['Bruce Springsteen', 'Born to Run', 1975],
  ['Bruce Springsteen', 'Born in the U.S.A.', 1984],
  ['Bruce Springsteen', 'Darkness on the Edge of Town', 1978],
  ['Queen', 'A Night at the Opera', 1975],
  ['Aretha Franklin', 'I Never Loved a Man the Way I Love You', 1967],
  ['Sly and the Family Stone', "There's a Riot Goin' On", 1971],
  ['The Band', 'Music from Big Pink', 1968],
  ['James Brown', 'Live at the Apollo', 1963],
  ['Al Green', "Call Me", 1973],
  ['Michael Jackson', 'Thriller', 1982],
  ['Michael Jackson', 'Off the Wall', 1979],
  ['Michael Jackson', 'Bad', 1987],
  ['Prince', 'Purple Rain', 1984],
  ['Prince', 'Sign o’ the Times', 1987],
  ['Prince', '1999', 1982],
  ['Madonna', 'Like a Prayer', 1989],
  ['U2', 'The Joshua Tree', 1987],
  ['U2', 'Achtung Baby', 1991],
  ['R.E.M.', 'Automatic for the People', 1992],
  ['Metallica', 'Master of Puppets', 1986],
  ['Metallica', 'Ride the Lightning', 1984],
  ['Metallica', 'Metallica (The Black Album)', 1991],
  ['Guns N’ Roses', 'Appetite for Destruction', 1987],
  ['Run-DMC', 'Raising Hell', 1986],
  ['Public Enemy', 'It Takes a Nation of Millions to Hold Us Back', 1988],
  ['The Smiths', 'The Queen Is Dead', 1986],
  ['New Order', 'Power, Corruption & Lies', 1983],
  ['Depeche Mode', 'Violator', 1990],
  ['Kate Bush', 'Hounds of Love', 1985],
  ['Def Leppard', 'Hysteria', 1987],
  ['AC/DC', 'Back in Black', 1980],
  ['Iron Maiden', 'The Number of the Beast', 1982],
  ['Whitney Houston', 'Whitney Houston', 1985],
  ['Tracy Chapman', 'Tracy Chapman', 1988],
  ['Nirvana', 'Nevermind', 1991],
  ['Nirvana', 'In Utero', 1993],
  ['Pearl Jam', 'Ten', 1991],
  ['Radiohead', 'OK Computer', 1997],
  ['Radiohead', 'The Bends', 1995],
  ['Radiohead', 'Kid A', 2000],
  ['Radiohead', 'In Rainbows', 2007],
  ['My Bloody Valentine', 'Loveless', 1991],
  ['Pixies', 'Doolittle', 1989],
  ['Beastie Boys', "Paul's Boutique", 1989],
  ['Beastie Boys', 'Ill Communication', 1994],
  ['Wu-Tang Clan', 'Enter the Wu-Tang (36 Chambers)', 1993],
  ['Nas', 'Illmatic', 1994],
  ['The Notorious B.I.G.', 'Ready to Die', 1994],
  ['2Pac', 'All Eyez on Me', 1996],
  ['Dr. Dre', 'The Chronic', 1992],
  ['Snoop Dogg', 'Doggystyle', 1993],
  ['A Tribe Called Quest', 'The Low End Theory', 1991],
  ['Portishead', 'Dummy', 1994],
  ['Massive Attack', 'Blue Lines', 1991],
  ['Massive Attack', 'Mezzanine', 1998],
  ['Björk', 'Homogenic', 1997],
  ['Alanis Morissette', 'Jagged Little Pill', 1995],
  ['Oasis', 'Definitely Maybe', 1994],
  ['Oasis', "(What's the Story) Morning Glory?", 1995],
  ['Blur', 'Parklife', 1994],
  ['Weezer', 'Weezer (The Blue Album)', 1994],
  ['Green Day', 'Dookie', 1994],
  ['Smashing Pumpkins', 'Mellon Collie and the Infinite Sadness', 1995],
  ['Smashing Pumpkins', 'Siamese Dream', 1993],
  ['Soundgarden', 'Superunknown', 1994],
  ['Alice in Chains', 'Dirt', 1992],
  ['Rage Against the Machine', 'Rage Against the Machine', 1992],
  ['Foo Fighters', 'The Colour and the Shape', 1997],
  ['Jeff Buckley', 'Grace', 1994],
  ['PJ Harvey', 'To Bring You My Love', 1995],
  ['Fiona Apple', 'Tidal', 1996],
  ['Lauryn Hill', 'The Miseducation of Lauryn Hill', 1998],
  ["D'Angelo", 'Voodoo', 2000],
  ['OutKast', 'Aquemini', 1998],
  ['OutKast', 'Stankonia', 2000],
  ['Daft Punk', 'Homework', 1997],
  ['Daft Punk', 'Discovery', 2001],
  ['Daft Punk', 'Random Access Memories', 2013],
  ['The Prodigy', 'The Fat of the Land', 1997],
  ['Aphex Twin', 'Selected Ambient Works 85-92', 1992],
  ['The Strokes', 'Is This It', 2001],
  ['The White Stripes', 'Elephant', 2003],
  ['Arcade Fire', 'Funeral', 2004],
  ['Kanye West', 'The College Dropout', 2004],
  ['Kanye West', 'Late Registration', 2005],
  ['Kanye West', 'My Beautiful Dark Twisted Fantasy', 2010],
  ['Kanye West', 'Yeezus', 2013],
  ['Jay-Z', 'The Blueprint', 2001],
  ['Jay-Z', 'The Black Album', 2003],
  ['Eminem', 'The Marshall Mathers LP', 2000],
  ['Interpol', 'Turn on the Bright Lights', 2002],
  ['Yeah Yeah Yeahs', 'Fever to Tell', 2003],
  ['LCD Soundsystem', 'Sound of Silver', 2007],
  ['Amy Winehouse', 'Back to Black', 2006],
  ['Gorillaz', 'Demon Days', 2005],
  ['Modest Mouse', 'The Moon & Antarctica', 2000],
  ['Sufjan Stevens', 'Illinois', 2005],
  ['Bon Iver', 'For Emma, Forever Ago', 2007],
  ['Bon Iver', 'Bon Iver, Bon Iver', 2011],
  ['Vampire Weekend', 'Vampire Weekend', 2008],
  ['Vampire Weekend', 'Modern Vampires of the City', 2013],
  ['MGMT', 'Oracular Spectacular', 2007],
  ['Death Cab for Cutie', 'Transatlanticism', 2003],
  ['My Chemical Romance', 'The Black Parade', 2006],
  ['Fleet Foxes', 'Fleet Foxes', 2008],
  ['Lorde', 'Pure Heroine', 2013],
  ['Kendrick Lamar', 'good kid, m.A.A.d city', 2012],
  ['Kendrick Lamar', 'To Pimp a Butterfly', 2015],
  ['Kendrick Lamar', 'DAMN.', 2017],
  ['Kendrick Lamar', 'Mr. Morale & the Big Steppers', 2022],
  ['Frank Ocean', 'channel ORANGE', 2012],
  ['Frank Ocean', 'Blonde', 2016],
  ['Beyoncé', 'Lemonade', 2016],
  ['Beyoncé', 'Beyoncé', 2013],
  ['Beyoncé', 'Renaissance', 2022],
  ['Taylor Swift', '1989', 2014],
  ['Taylor Swift', 'Red', 2012],
  ['Taylor Swift', 'folklore', 2020],
  ['Adele', '21', 2011],
  ['Adele', '25', 2015],
  ['Arctic Monkeys', 'AM', 2013],
  ['Tame Impala', 'Currents', 2015],
  ['The War on Drugs', 'Lost in the Dream', 2014],
  ['Chance the Rapper', 'Coloring Book', 2016],
  ['Drake', 'Take Care', 2011],
  ['Billie Eilish', 'When We All Fall Asleep, Where Do We Go?', 2019],
  ['SZA', 'Ctrl', 2017],
  ['SZA', 'SOS', 2022],
  ['Solange', 'A Seat at the Table', 2016],
  ['Childish Gambino', 'Because the Internet', 2013],
  ['Mac Miller', 'Swimming', 2018],
  ['Travis Scott', 'Astroworld', 2018],
  ['Phoebe Bridgers', 'Punisher', 2020],
  ['Harry Styles', 'Fine Line', 2019],
  ['Olivia Rodrigo', 'SOUR', 2021],
  ['boygenius', 'the record', 2023],
  ['Bad Bunny', 'Un Verano Sin Ti', 2022],
  ['Miles Davis', 'Kind of Blue', 1959],
  ['John Coltrane', 'A Love Supreme', 1965],
  ['Dave Brubeck', 'Time Out', 1959],
  ['Nina Simone', 'I Put a Spell on You', 1965],
  ['Johnny Cash', 'At Folsom Prison', 1968],
  ['Willie Nelson', 'Red Headed Stranger', 1975],
  ['Dolly Parton', 'Coat of Many Colors', 1971],
  ['ABBA', 'Arrival', 1976],
  ['Fela Kuti', 'Zombie', 1976],
  ['Bob Marley & The Wailers', 'Exodus', 1977],
  ['Bob Marley & The Wailers', 'Legend', 1984],
  ['The Cure', 'Disintegration', 1989],
  ['Sonic Youth', 'Daydream Nation', 1988],
  ['Slint', 'Spiderland', 1991],
  ['Kraftwerk', 'Trans-Europe Express', 1977],
  ['Brian Eno', 'Another Green World', 1975],
  ['King Crimson', 'In the Court of the Crimson King', 1969],
  ['Yes', 'Close to the Edge', 1972],
  ['Genesis', 'Selling England by the Pound', 1973],
  ['Rush', 'Moving Pictures', 1981],
  ['Black Sabbath', 'Paranoid', 1970],
  ['Judas Priest', 'British Steel', 1980],
  ['Slayer', 'Reign in Blood', 1986],
  ['Pantera', 'Vulgar Display of Power', 1992],
  ['Nine Inch Nails', 'The Downward Spiral', 1994],
  ['Tool', 'Lateralus', 2001],
  ['System of a Down', 'Toxicity', 2001],

  // ---- Hip-Hop / Rap: old school & golden age ----
  ['Run-D.M.C.', 'Run-D.M.C.', 1984],
  ['Beastie Boys', 'Licensed to Ill', 1986],
  ['Public Enemy', 'Fear of a Black Planet', 1990],
  ['Eric B. & Rakim', 'Paid in Full', 1987],
  ['Boogie Down Productions', 'Criminal Minded', 1987],
  ['Big Daddy Kane', 'Long Live the Kane', 1988],
  ['Slick Rick', 'The Great Adventures of Slick Rick', 1988],
  ['De La Soul', '3 Feet High and Rising', 1989],
  ['A Tribe Called Quest', "People's Instinctive Travels and the Paths of Rhythm", 1990],
  ['Gang Starr', 'Daily Operation', 1992],
  ['Ultramagnetic MCs', 'Critical Beatdown', 1988],
  ['EPMD', 'Strictly Business', 1988],
  ['Queen Latifah', 'All Hail the Queen', 1989],
  ['MC Lyte', 'Lyte as a Rock', 1988],
  ['Salt-N-Pepa', 'Hot, Cool & Vicious', 1986],
  // ---- Hip-Hop / Rap: 90s ----
  ['Cypress Hill', 'Cypress Hill', 1991],
  ['Ice Cube', "AmeriKKKa's Most Wanted", 1990],
  ['Ice Cube', 'Death Certificate', 1991],
  ['Geto Boys', "We Can't Be Stopped", 1991],
  ['Wu-Tang Clan', 'Wu-Tang Forever', 1997],
  ['Raekwon', 'Only Built 4 Cuban Linx...', 1995],
  ['GZA', 'Liquid Swords', 1995],
  ['Method Man', 'Tical', 1994],
  ['Mobb Deep', 'The Infamous', 1995],
  ['Nas', 'It Was Written', 1996],
  ['Jay-Z', 'Reasonable Doubt', 1996],
  ['Jay-Z', "Vol. 2... Hard Knock Life", 1998],
  ['The Notorious B.I.G.', 'Life After Death', 1997],
  ['Big L', 'Lifestylez ov da Poor & Dangerous', 1995],
  ['Big Pun', 'Capital Punishment', 1998],
  ['Fugees', 'The Score', 1996],
  ['OutKast', 'Southernplayalisticadillacmuzik', 1994],
  ['Goodie Mob', 'Soul Food', 1995],
  ['UGK', 'Ridin’ Dirty', 1996],
  ['Three 6 Mafia', 'Mystic Stylez', 1995],
  ['8Ball & MJG', "Comin' Out Hard", 1993],
  ['Scarface', 'The Diary', 1994],
  ['Snoop Dogg', 'Tha Doggfather', 1996],
  ['Warren G', 'Regulate...G Funk Era', 1994],
  ['2Pac', 'Me Against the World', 1995],
  ['2Pac', "The Don Killuminati: The 7 Day Theory", 1996],
  ['Bone Thugs-n-Harmony', "E. 1999 Eternal", 1995],
  ['Missy Elliott', 'Supa Dupa Fly', 1997],
  ['Black Star', 'Mos Def & Talib Kweli Are Black Star', 1998],
  ['Mos Def', 'Black on Both Sides', 1999],
  ['Jurassic 5', 'Quality Control', 2000],
  ['DMX', "It's Dark and Hell Is Hot", 1998],
  ['Busta Rhymes', 'The Coming', 1996],
  ['Redman', 'Whut? Thee Album', 1992],
  ['Eminem', 'The Slim Shady LP', 1999],
  ['Foxy Brown', 'Ill Na Na', 1996],
  ['Lil’ Kim', 'Hard Core', 1996],
  ['Da Brat', 'Funkdafied', 1994],
  ['Master P', 'Ghetto D', 1997],
  // ---- Hip-Hop / Rap: 2000s ----
  ['50 Cent', "Get Rich or Die Tryin'", 2003],
  ['The Game', 'The Documentary', 2005],
  ['Lil Wayne', 'Tha Carter II', 2005],
  ['T.I.', 'Trap Muzik', 2003],
  ['T.I.', 'King', 2006],
  ['Young Jeezy', "Let's Get It: Thug Motivation 101", 2005],
  ['Clipse', 'Hell Hath No Fury', 2006],
  ['Ludacris', 'Word of Mouf', 2001],
  ['Nelly', 'Country Grammar', 2000],
  ['Cam’ron', 'Purple Haze', 2004],
  ['The Diplomats', 'Diplomatic Immunity', 2003],
  ['Jadakiss', 'Kiss of Death', 2004],
  ['Kanye West', 'Graduation', 2007],
  ['Kanye West', '808s & Heartbreak', 2008],
  ['Lupe Fiasco', 'Food & Liquor', 2006],
  ['Common', 'Be', 2005],
  ['Talib Kweli', 'Quality', 2002],
  ['Atmosphere', 'God Loves Ugly', 2002],
  ['MF DOOM', 'Operation: Doomsday', 1999],
  ['Madvillain', 'Madvillainy', 2004],
  ['Little Brother', 'The Listening', 2003],
  ['Ghostface Killah', 'Fishscale', 2006],
  ['Ghostface Killah', 'Supreme Clientele', 2000],
  ['Rick Ross', 'Port of Miami', 2006],
  ['Gucci Mane', 'Trap House', 2005],
  ['Dizzee Rascal', 'Boy in da Corner', 2003],
  ['M.I.A.', 'Kala', 2007],
  ['Nicki Minaj', 'Pink Friday', 2010],
  // ---- Hip-Hop / Rap: 2010s ----
  ['Kendrick Lamar', 'Section.80', 2011],
  ['J. Cole', 'Cole World: The Sideline Story', 2011],
  ['J. Cole', '2014 Forest Hills Drive', 2014],
  ['J. Cole', 'KOD', 2018],
  ['Drake', 'Nothing Was the Same', 2013],
  ['Drake', 'Scorpion', 2018],
  ['Chance the Rapper', 'Acid Rap', 2013],
  ['Vince Staples', "Summertime '06", 2015],
  ['Vince Staples', 'Big Fish Theory', 2017],
  ['Earl Sweatshirt', 'Doris', 2013],
  ['Earl Sweatshirt', "I Don't Like Shit, I Don't Go Outside", 2015],
  ['Tyler, the Creator', 'Goblin', 2011],
  ['Tyler, the Creator', 'Flower Boy', 2017],
  ['Tyler, the Creator', 'IGOR', 2019],
  ['Danny Brown', 'XXX', 2011],
  ['Danny Brown', 'Atrocity Exhibition', 2016],
  ['Future', 'DS2', 2015],
  ['Young Thug', 'Barter 6', 2015],
  ['Migos', 'Culture', 2017],
  ['Travis Scott', 'Rodeo', 2015],
  ['Playboi Carti', 'Die Lit', 2018],
  ['21 Savage', 'Issa Album', 2017],
  ['A$AP Rocky', 'Long.Live.A$AP', 2013],
  ['A$AP Rocky', 'Testing', 2018],
  ['Freddie Gibbs & Madlib', 'Piñata', 2014],
  ['Freddie Gibbs & Madlib', 'Bandana', 2019],
  ['Run the Jewels', 'Run the Jewels 2', 2014],
  ['Death Grips', 'The Money Store', 2012],
  ['Noname', 'Telefone', 2016],
  ['Isaiah Rashad', "The Sun's Tirade", 2016],
  ['Schoolboy Q', 'Oxymoron', 2014],
  ['Ab-Soul', 'Control System', 2012],
  ['JID', 'The Never Story', 2017],
  ['Denzel Curry', "TA13OO", 2018],
  ['Little Simz', 'Grey Area', 2019],
  ['Dave', 'Psychodrama', 2019],
  ['Stormzy', 'Gang Signs & Prayer', 2017],
  ['Skepta', 'Konnichiwa', 2016],
  ['Eve', "Let There Be Eve...Ruff Ryders' First Lady", 1999],
  ['Trina', 'Da Baddest Bitch', 2000],
  // ---- Hip-Hop / Rap: 2020s ----
  ['Tyler, the Creator', 'Call Me If You Get Lost', 2021],
  ['J. Cole', 'The Off-Season', 2021],
  ['Doja Cat', 'Planet Her', 2021],
  ['Baby Keem', 'The Melodic Blue', 2021],
  ['Roddy Ricch', 'Please Excuse Me for Being Antisocial', 2019],
  ['Pop Smoke', 'Shoot for the Stars, Aim for the Moon', 2020],
  ['Nas', "King's Disease", 2020],
  ['Freddie Gibbs', 'Alfredo', 2020],
  ['Little Simz', 'Sometimes I Might Be Introvert', 2021],
  ['Kanye West', 'Donda', 2021],
  ['Drake', 'Certified Lover Boy', 2021],
  ['Megan Thee Stallion', 'Good News', 2020],
  ['Cardi B', 'Invasion of Privacy', 2018],
  ['Killer Mike', 'Michael', 2023],
  ['Danny Brown', 'Quaranta', 2023],

  // ---- R&B / Soul ----
  ['Otis Redding', 'Otis Blue', 1965],
  ['Sam Cooke', "Portrait of a Legend 1951-1964", 1964],
  ['Curtis Mayfield', 'Curtis', 1970],
  ['The Isley Brothers', "3+3", 1973],
  ['Earth, Wind & Fire', "That's the Way of the World", 1975],
  ['The Spinners', 'Spinners', 1973],
  ['Chic', "C'est Chic", 1978],
  ['Teddy Pendergrass', 'Teddy', 1979],
  ['Anita Baker', 'Rapture', 1986],
  ['Luther Vandross', 'Never Too Much', 1981],
  ['Sade', 'Diamond Life', 1984],
  ['Janet Jackson', 'Rhythm Nation 1814', 1989],
  ['Janet Jackson', "janet.", 1993],
  ['Whitney Houston', "Whitney", 1987],
  ['Mary J. Blige', "My Life", 1994],
  ['Mary J. Blige', 'Share My World', 1997],
  ['TLC', 'CrazySexyCool', 1994],
  ['Toni Braxton', 'Toni Braxton', 1993],
  ['Brandy', 'Never Say Never', 1998],
  ['Aaliyah', 'One in a Million', 1996],
  ['Aaliyah', 'Aaliyah', 2001],
  ['Usher', 'Confessions', 2004],
  ['Alicia Keys', 'Songs in A Minor', 2001],
  ['Erykah Badu', 'Baduizm', 1997],
  ['Erykah Badu', "Mama's Gun", 2000],
  ["D'Angelo", 'Brown Sugar', 1995],
  ['Maxwell', "Maxwell's Urban Hang Suite", 1996],
  ['Jill Scott', 'Who Is Jill Scott? Words and Sounds Vol. 1', 2000],
  ['India.Arie', 'Acoustic Soul', 2001],
  ['John Legend', 'Get Lifted', 2004],
  ['Amy Winehouse', 'Frank', 2003],
  ['Frank Ocean', 'Nostalgia, Ultra', 2011],
  ['The Weeknd', 'House of Balloons', 2011],
  ['The Weeknd', 'Beauty Behind the Madness', 2015],
  ['The Weeknd', 'After Hours', 2020],
  ['Miguel', 'Kaleidoscope Dream', 2012],
  ['Frank Ocean', 'Endless', 2016],
  ['H.E.R.', 'H.E.R.', 2017],
  ['Daniel Caesar', 'Freudian', 2017],
  ['Summer Walker', 'Over It', 2019],
  ['Snoh Aalegra', "Ugh, Those Feels Again", 2019],
  ['Giveon', 'Take Time', 2020],
  ['Anderson .Paak', 'Malibu', 2016],
  ['Silk Sonic', 'An Evening with Silk Sonic', 2021],
  ['Victoria Monét', 'Jaguar II', 2023],
  ['Solange', 'When I Get Home', 2019],
  ['Kehlani', 'SweetSexySavage', 2017],
  ['Ari Lennox', 'Shea Butter Baby', 2019],
  ['Jazmine Sullivan', 'Heaux Tales', 2021],
  ['Chris Brown', 'Exclusive', 2007],
  ['Ne-Yo', 'In My Own Words', 2006],
  ['Trey Songz', 'Ready', 2009],
  ['Ciara', 'Goodies', 2004],
  ['Beyoncé', 'Dangerously in Love', 2003],
  ['Beyoncé', 'I Am... Sasha Fierce', 2008],
  ['Destiny’s Child', 'The Writing’s on the Wall', 1999],
  ['En Vogue', 'Funky Divas', 1992],
  ['Boyz II Men', 'II', 1994],
  ['Jodeci', 'Forever My Lady', 1991],
  ['Al Green', "Let's Stay Together", 1972],
  ['Marvin Gaye', "Let's Get It On", 1973],
  ['Stevie Wonder', 'Talking Book', 1972],

  // ---- Pop ----
  ['Cyndi Lauper', "She's So Unusual", 1983],
  ['George Michael', 'Faith', 1987],
  ['Wham!', 'Make It Big', 1984],
  ['Duran Duran', 'Rio', 1982],
  ['Culture Club', 'Colour by Numbers', 1983],
  ['Tears for Fears', 'Songs from the Big Chair', 1985],
  ['Phil Collins', 'No Jacket Required', 1985],
  ['Lionel Richie', 'Can’t Slow Down', 1983],
  ['Prince', 'Around the World in a Day', 1985],
  ['Paula Abdul', 'Forever Your Girl', 1988],
  ['Mariah Carey', 'Mariah Carey', 1990],
  ['Mariah Carey', 'Daydream', 1995],
  ['Celine Dion', 'Falling into You', 1996],
  ['Spice Girls', 'Spice', 1996],
  ['Backstreet Boys', 'Millennium', 1999],
  ['*NSYNC', 'No Strings Attached', 2000],
  ['Britney Spears', "...Baby One More Time", 1999],
  ['Britney Spears', 'Oops!... I Did It Again', 2000],
  ['Christina Aguilera', 'Stripped', 2002],
  ['Shakira', 'Laundry Service', 2001],
  ['Jennifer Lopez', 'On the 6', 1999],
  ['Kylie Minogue', 'Fever', 2001],
  ['Robbie Williams', 'Life thru a Lens', 1997],
  ['Coldplay', 'Parachutes', 2000],
  ['Coldplay', 'A Rush of Blood to the Head', 2002],
  ['Coldplay', 'Viva la Vida', 2008],
  ['Maroon 5', 'Songs About Jane', 2002],
  ['OneRepublic', 'Dreaming Out Loud', 2007],
  ['Katy Perry', 'Teenage Dream', 2010],
  ['Lady Gaga', 'The Fame', 2008],
  ['Lady Gaga', 'Born This Way', 2011],
  ['Rihanna', 'Good Girl Gone Bad', 2007],
  ['Rihanna', 'Anti', 2016],
  ['Bruno Mars', "Doo-Wops & Hooligans", 2010],
  ['Bruno Mars', '24K Magic', 2016],
  ['Ed Sheeran', '÷ (Divide)', 2017],
  ['Ed Sheeran', 'x (Multiply)', 2014],
  ['Sam Smith', 'In the Lonely Hour', 2014],
  ['Adele', '30', 2021],
  ['Dua Lipa', 'Future Nostalgia', 2020],
  ['Ariana Grande', 'thank u, next', 2019],
  ['Ariana Grande', 'Sweetener', 2018],
  ['Selena Gomez', 'Rare', 2020],
  ['Demi Lovato', 'Confident', 2015],
  ['Miley Cyrus', 'Bangerz', 2013],
  ['Katy Perry', 'One of the Boys', 2008],
  ['Justin Bieber', 'Purpose', 2015],
  ['Justin Timberlake', 'FutureSex/LoveSounds', 2006],
  ['Justin Timberlake', 'Justified', 2002],
  ['P!nk', "M!ssundaztood", 2001],
  ['Gwen Stefani', 'Love. Angel. Music. Baby.', 2004],
  ['Charli XCX', 'Brat', 2024],
  ['Sabrina Carpenter', 'Short n’ Sweet', 2024],
  ['Chappell Roan', 'The Rise and Fall of a Midwest Princess', 2023],
  ['Lorde', 'Melodrama', 2017],
  ['Halsey', 'Badlands', 2015],
  ['Sia', '1000 Forms of Fear', 2014],
  ['Carly Rae Jepsen', 'Emotion', 2015],
  ['Troye Sivan', 'Bloom', 2018],
  ['Years & Years', 'Communion', 2015],

  // ---- Rock (classic, hard, alt, indie, punk) ----
  ['The Who', 'Tommy', 1969],
  ['The Kinks', 'The Kinks Are the Village Green Preservation Society', 1968],
  ['Cream', 'Disraeli Gears', 1967],
  ['Jimi Hendrix Experience', 'Are You Experienced', 1967],
  ['Jimi Hendrix Experience', 'Electric Ladyland', 1968],
  ['The Doors', 'The Doors', 1967],
  ['Jefferson Airplane', 'Surrealistic Pillow', 1967],
  ['Grateful Dead', 'American Beauty', 1970],
  ['The Allman Brothers Band', 'At Fillmore East', 1971],
  ['Derek and the Dominos', 'Layla and Other Assorted Love Songs', 1970],
  ['Deep Purple', 'Machine Head', 1972],
  ['Aerosmith', 'Toys in the Attic', 1975],
  ['Boston', 'Boston', 1976],
  ['Foreigner', 'Foreigner', 1977],
  ['Journey', 'Escape', 1981],
  ['Kansas', 'Leftoverture', 1976],
  ['Styx', 'The Grand Illusion', 1977],
  ['Electric Light Orchestra', 'Out of the Blue', 1977],
  ['Supertramp', 'Breakfast in America', 1979],
  ['Fleetwood Mac', 'Tusk', 1979],
  ['Dire Straits', 'Brothers in Arms', 1985],
  ['The Police', 'Synchronicity', 1983],
  ['Talking Heads', "Fear of Music", 1979],
  ['Talking Heads', 'Stop Making Sense', 1984],
  ['Pretenders', 'Pretenders', 1980],
  ['Blondie', 'Parallel Lines', 1978],
  ['Television', 'Marquee Moon', 1977],
  ['Ramones', 'Ramones', 1976],
  ['Sex Pistols', 'Never Mind the Bollocks, Here’s the Sex Pistols', 1977],
  ['Buzzcocks', 'Singles Going Steady', 1979],
  ['The Jam', 'All Mod Cons', 1978],
  ['Wire', 'Pink Flag', 1977],
  ['Joy Division', 'Unknown Pleasures', 1979],
  ['Joy Division', 'Closer', 1980],
  ['Echo & the Bunnymen', 'Ocean Rain', 1984],
  ['The Chameleons', 'Script of the Bridge', 1983],
  ['Siouxsie and the Banshees', 'Juju', 1981],
  ['R.E.M.', 'Murmur', 1983],
  ['R.E.M.', 'Document', 1987],
  ['The Replacements', 'Let It Be', 1984],
  ['Hüsker Dü', 'Zen Arcade', 1984],
  ['Dinosaur Jr.', 'You’re Living All Over Me', 1987],
  ['Fugazi', 'Repeater', 1990],
  ['Minor Threat', 'Complete Discography', 1989],
  ['Black Flag', 'Damaged', 1981],
  ['Dead Kennedys', 'Fresh Fruit for Rotting Vegetables', 1980],
  ['Bad Brains', 'Bad Brains', 1982],
  ['Faith No More', 'The Real Thing', 1989],
  ['Jane’s Addiction', 'Nothing’s Shocking', 1988],
  ['Red Hot Chili Peppers', 'Blood Sugar Sex Magik', 1991],
  ['Red Hot Chili Peppers', 'Californication', 1999],
  ['Stone Temple Pilots', 'Core', 1992],
  ['Alice in Chains', 'Facelift', 1990],
  ['Soundgarden', 'Badmotorfinger', 1991],
  ['Screaming Trees', 'Sweet Oblivion', 1992],
  ['Mudhoney', 'Superfuzz Bigmuff', 1988],
  ['The Smashing Pumpkins', 'Gish', 1991],
  ['Weezer', 'Pinkerton', 1996],
  ['Beck', 'Odelay', 1996],
  ['Beck', 'Sea Change', 2002],
  ['Radiohead', 'Amnesiac', 2001],
  ['Blur', 'The Great Escape', 1995],
  ['Pulp', 'Different Class', 1995],
  ['Suede', 'Suede', 1993],
  ['Elastica', 'Elastica', 1995],
  ['Supergrass', 'I Should Coco', 1995],
  ['Manic Street Preachers', 'The Holy Bible', 1994],
  ['Stereophonics', 'Word Gets Around', 1997],
  ['Travis', 'The Man Who', 1999],
  ['Muse', 'Origin of Symmetry', 2001],
  ['Muse', 'Black Holes and Revelations', 2006],
  ['The Verve', 'Urban Hymns', 1997],
  ['Kasabian', 'Kasabian', 2004],
  ['Franz Ferdinand', 'Franz Ferdinand', 2004],
  ['Bloc Party', 'Silent Alarm', 2005],
  ['Arctic Monkeys', "Whatever People Say I Am, That's What I'm Not", 2006],
  ['The Libertines', 'Up the Bracket', 2002],
  ['Editors', 'The Back Room', 2005],
  ['The Killers', 'Hot Fuss', 2004],
  ['Kings of Leon', 'Only by the Night', 2008],
  ['My Morning Jacket', 'Z', 2005],
  ['Modest Mouse', 'Good News for People Who Love Bad News', 2004],
  ['The Shins', 'Oh, Inverted World', 2001],
  ['Death Cab for Cutie', 'Plans', 2005],
  ['Spoon', 'Ga Ga Ga Ga Ga', 2007],
  ['Wilco', 'Yankee Hotel Foxtrot', 2002],
  ['The National', 'Boxer', 2007],
  ['The National', 'High Violet', 2010],
  ['Bon Iver', 'i,i', 2019],
  ['Grizzly Bear', 'Veckatimest', 2009],
  ['Animal Collective', 'Merriweather Post Pavilion', 2009],
  ['Vampire Weekend', 'Father of the Bride', 2019],
  ['Alabama Shakes', 'Boys & Girls', 2012],
  ['The Black Keys', 'Brothers', 2010],
  ['The Black Keys', 'El Camino', 2011],
  ['The White Stripes', 'White Blood Cells', 2001],
  ['The Strokes', 'Room on Fire', 2003],
  ['Interpol', 'Antics', 2004],
  ['Yeah Yeah Yeahs', 'It’s Blitz!', 2009],
  ['MGMT', 'Congratulations', 2010],
  ['Tame Impala', 'Lonerism', 2012],
  ['Tame Impala', 'The Slow Rush', 2020],
  ['Foster the People', 'Torches', 2011],
  ['Cage the Elephant', 'Melophobia', 2013],
  ['Twenty One Pilots', 'Blurryface', 2015],
  ['Imagine Dragons', 'Night Visions', 2012],
  ['Florence + the Machine', 'Lungs', 2009],
  ['Florence + the Machine', 'Ceremonials', 2011],
  ['Arcade Fire', 'The Suburbs', 2010],
  ['Arcade Fire', 'Reflektor', 2013],
  ['LCD Soundsystem', 'This Is Happening', 2010],
  ['Fleet Foxes', 'Helplessness Blues', 2011],
  ['The War on Drugs', 'A Deeper Understanding', 2017],
  ['Big Thief', 'U.F.O.F.', 2019],
  ['Phoebe Bridgers', 'Stranger in the Alps', 2017],
  ['boygenius', 'the record', 2023],
  ['Wolf Alice', 'Visions of a Life', 2017],
  ['Idles', 'Joy as an Act of Resistance', 2018],
  ['Fontaines D.C.', 'Dogrel', 2019],
  ['Turnstile', 'Glow On', 2021],

  // ---- Metal ----
  ['Metallica', 'Kill ’Em All', 1983],
  ['Megadeth', 'Rust in Peace', 1990],
  ['Anthrax', 'Among the Living', 1987],
  ['Slayer', 'Seasons in the Abyss', 1990],
  ['Iron Maiden', 'The Number of the Beast', 1982],
  ['Iron Maiden', 'Powerslave', 1984],
  ['Judas Priest', 'Painkiller', 1990],
  ['Black Sabbath', 'Master of Reality', 1971],
  ['Motörhead', 'Ace of Spades', 1980],
  ['Venom', 'Black Metal', 1982],
  ['Sepultura', 'Roots', 1996],
  ['Death', 'Symbolic', 1995],
  ['Morbid Angel', 'Altars of Madness', 1989],
  ['Mayhem', 'De Mysteriis Dom Sathanas', 1994],
  ['Emperor', 'In the Nightside Eclipse', 1994],
  ['Opeth', 'Blackwater Park', 2001],
  ['Meshuggah', 'Nothing', 2002],
  ['Lamb of God', 'Ashes of the Wake', 2004],
  ['Mastodon', 'Leviathan', 2004],
  ['Mastodon', 'Crack the Skye', 2009],
  ['Gojira', 'L’Enfant Sauvage', 2012],
  ['Deftones', 'White Pony', 2000],
  ['Korn', 'Korn', 1994],
  ['Slipknot', 'Slipknot', 1999],
  ['Slipknot', 'Iowa', 2001],
  ['Disturbed', 'The Sickness', 2000],
  ['Linkin Park', 'Hybrid Theory', 2000],
  ['Linkin Park', 'Meteora', 2003],
  ['Rage Against the Machine', 'Evil Empire', 1996],
  ['System of a Down', 'System of a Down', 1998],
  ['Avenged Sevenfold', 'City of Evil', 2005],
  ['Trivium', 'Ascendancy', 2005],
  ['Killswitch Engage', 'The End of Heartache', 2004],
  ['Bring Me the Horizon', "Sempiternal", 2013],
  ['Ghost', 'Meliora', 2015],
  ['Judas Priest', 'Screaming for Vengeance', 1982],
  ['Dio', 'Holy Diver', 1983],
  ['Pantera', 'Far Beyond Driven', 1994],
  ['Alice in Chains', 'Dirt', 1992],
  ['Type O Negative', 'Bloody Kisses', 1993],
  ['Rammstein', 'Mutter', 2001],

  // ---- Country ----
  ['Hank Williams', '40 Greatest Hits', 1978],
  ['Patsy Cline', 'Showcase', 1961],
  ['Merle Haggard', 'Mama Tried', 1968],
  ['Loretta Lynn', "Coal Miner's Daughter", 1971],
  ['Waylon Jennings', 'Honky Tonk Heroes', 1973],
  ['Willie Nelson', 'Stardust', 1978],
  ['The Highwaymen', 'Highwayman', 1985],
  ['George Strait', 'Strait Country', 1981],
  ['Randy Travis', 'Storms of Life', 1986],
  ['Reba McEntire', 'Whoever’s in New England', 1986],
  ['Alan Jackson', 'Don’t Rock the Jukebox', 1991],
  ['Garth Brooks', 'No Fences', 1990],
  ['Garth Brooks', 'Ropin’ the Wind', 1991],
  ['Brooks & Dunn', 'Brand New Man', 1991],
  ['Vince Gill', 'When I Call Your Name', 1989],
  ['Trisha Yearwood', 'Trisha Yearwood', 1991],
  ['Shania Twain', 'Come On Over', 1997],
  ['Faith Hill', 'Breathe', 1999],
  ['Dixie Chicks', 'Wide Open Spaces', 1998],
  ['Dixie Chicks', 'Fly', 1999],
  ['Tim McGraw', 'Not a Moment Too Soon', 1994],
  ['Toby Keith', 'How Do You Like Me Now?!', 1999],
  ['Kenny Chesney', 'No Shoes, No Shirt, No Problems', 2002],
  ['Rascal Flatts', 'Melt', 2002],
  ['Carrie Underwood', 'Some Hearts', 2005],
  ['Sugarland', 'Enjoy the Ride', 2006],
  ['Lady A', 'Need You Now', 2010],
  ['Miranda Lambert', 'Revolution', 2009],
  ['Miranda Lambert', 'The Weight of These Wings', 2016],
  ['Taylor Swift', 'Taylor Swift', 2006],
  ['Taylor Swift', 'Fearless', 2008],
  ['Taylor Swift', 'Speak Now', 2010],
  ['Zac Brown Band', 'The Foundation', 2008],
  ['Eric Church', 'Chief', 2011],
  ['Jason Aldean', 'My Kinda Party', 2010],
  ['Luke Bryan', 'Crash My Party', 2013],
  ['Blake Shelton', 'Red River Blue', 2011],
  ['Kacey Musgraves', 'Same Trailer Different Park', 2013],
  ['Kacey Musgraves', 'Golden Hour', 2018],
  ['Chris Stapleton', 'Traveller', 2015],
  ['Sturgill Simpson', "Metamodern Sounds in Country Music", 2014],
  ['Jason Isbell', 'Southeastern', 2013],
  ['Zach Bryan', 'American Heartbreak', 2022],
  ['Morgan Wallen', 'Dangerous: The Double Album', 2021],
  ['Cody Johnson', 'Human: The Double Album', 2021],
  ['Lainey Wilson', 'Bell Bottom Country', 2022],
  ['Beyoncé', 'Cowboy Carter', 2024],
  ['Dolly Parton', 'Jolene', 1974],
  ['Emmylou Harris', 'Wrecking Ball', 1995],
  ['Lucinda Williams', 'Car Wheels on a Gravel Road', 1998],

  // ---- Electronic / Dance ----
  ['Kraftwerk', 'The Man-Machine', 1978],
  ['Kraftwerk', 'Computer World', 1981],
  ['Depeche Mode', 'Violator', 1990],
  ['New Order', 'Technique', 1989],
  ['The Chemical Brothers', 'Dig Your Own Hole', 1997],
  ['The Chemical Brothers', "Surrender", 1999],
  ['Fatboy Slim', "You've Come a Long Way, Baby", 1998],
  ['Underworld', 'Dubnobasswithmyheadman', 1994],
  ['Orbital', 'In Sides', 1996],
  ['Leftfield', 'Leftism', 1995],
  ['Massive Attack', '100th Window', 2003],
  ['Tricky', 'Maxinquaye', 1995],
  ['Björk', 'Debut', 1993],
  ['Björk', 'Post', 1995],
  ['Björk', 'Vespertine', 2001],
  ['Moby', 'Play', 1999],
  ['Air', 'Moon Safari', 1998],
  ['Daft Punk', 'Human After All', 2005],
  ['Justice', '† (Cross)', 2007],
  ['Deadmau5', 'For Lack of a Better Name', 2009],
  ['Skrillex', 'Bangarang', 2011],
  ['Avicii', 'True', 2013],
  ['Calvin Harris', '18 Months', 2012],
  ['Disclosure', 'Settle', 2013],
  ['Flume', 'Flume', 2012],
  ['Odesza', 'In Return', 2014],
  ['Bonobo', 'Black Sands', 2010],
  ['Four Tet', 'There Is Love in You', 2010],
  ['Burial', 'Untrue', 2007],
  ['James Blake', 'James Blake', 2011],
  ['SBTRKT', 'SBTRKT', 2011],
  ['Jamie xx', 'In Colour', 2015],
  ['The xx', 'xx', 2009],
  ['Caribou', 'Swim', 2010],
  ['Aphex Twin', 'Drukqs', 2001],
  ['Boards of Canada', 'Music Has the Right to Children', 1998],
  ['Autechre', 'Tri Repetae', 1995],
  ['Squarepusher', 'Go Plastic', 2001],
  ['LCD Soundsystem', 'LCD Soundsystem', 2005],
  ['Hot Chip', 'The Warning', 2006],
  ['Cut Copy', 'In Ghost Colours', 2008],
  ['Röyksopp', 'Melody A.M.', 2001],
  ['Zedd', 'Clarity', 2012],
  ['Marshmello', 'Joytime', 2016],
  ['Porter Robinson', 'Worlds', 2014],
  ['Madeon', 'Adventure', 2015],
  ['ODESZA', 'A Moment Apart', 2017],

  // ---- Jazz ----
  ['Louis Armstrong', 'The Hot Fives and Hot Sevens', 1928],
  ['Duke Ellington', 'Ellington at Newport', 1956],
  ['Charlie Parker', 'Bird and Diz', 1952],
  ['Thelonious Monk', 'Brilliant Corners', 1957],
  ['Sonny Rollins', 'Saxophone Colossus', 1956],
  ['Bill Evans', 'Waltz for Debby', 1961],
  ['Art Blakey', 'Moanin’', 1959],
  ['Charles Mingus', 'Mingus Ah Um', 1959],
  ['Charles Mingus', 'The Black Saint and the Sinner Lady', 1963],
  ['Ornette Coleman', 'The Shape of Jazz to Come', 1959],
  ['John Coltrane', 'Giant Steps', 1960],
  ['John Coltrane', 'Blue Train', 1958],
  ['Herbie Hancock', 'Head Hunters', 1973],
  ['Herbie Hancock', 'Maiden Voyage', 1965],
  ['Wayne Shorter', 'Speak No Evil', 1966],
  ['Miles Davis', 'Bitches Brew', 1970],
  ['Miles Davis', 'In a Silent Way', 1969],
  ['Weather Report', 'Heavy Weather', 1977],
  ['Return to Forever', 'Romantic Warrior', 1976],
  ['Pat Metheny Group', 'Offramp', 1982],
  ['Chick Corea', 'Now He Sings, Now He Sobs', 1968],
  ['Cannonball Adderley', 'Somethin’ Else', 1958],
  ['Stan Getz & João Gilberto', 'Getz/Gilberto', 1964],
  ['Nina Simone', 'Wild Is the Wind', 1966],
  ['Ella Fitzgerald', 'Ella and Louis', 1956],
  ['Billie Holiday', 'Lady in Satin', 1958],
  ['Sarah Vaughan', 'Sarah Vaughan', 1954],
  ['Dexter Gordon', 'Go', 1962],
  ['Grant Green', 'Idle Moments', 1965],
  ['Wes Montgomery', 'The Incredible Jazz Guitar of Wes Montgomery', 1960],
  ['Kamasi Washington', 'The Epic', 2015],
  ['Robert Glasper', 'Black Radio', 2012],
  ['Esperanza Spalding', 'Emily’s D+Evolution', 2016],
  ['Snarky Puppy', 'We Like It Here', 2014],
  ['Norah Jones', 'Come Away with Me', 2002],
  ['Diana Krall', 'The Look of Love', 2001],

  // ---- Latin / Reggaeton ----
  ['Selena', 'Amor Prohibido', 1994],
  ['Gloria Estefan', 'Mi Tierra', 1993],
  ['Juan Gabriel', 'Recuerdos, Vol. II', 1985],
  ['Vicente Fernández', 'Un Mexicano en la México', 1984],
  ['Celia Cruz', 'Celia & Johnny', 1974],
  ['Rubén Blades', 'Siembra', 1978],
  ['Héctor Lavoe', 'La Voz', 1975],
  ['Marc Anthony', 'Todo a Su Tiempo', 1995],
  ['Juanes', 'Un Día Normal', 2002],
  ['Shakira', 'Dónde Están los Ladrones?', 1998],
  ['Café Tacvba', 'Re', 1994],
  ['Soda Stereo', 'Canción Animal', 1990],
  ['Maná', 'Sueños Líquidos', 1997],
  ['Daddy Yankee', 'Barrio Fino', 2004],
  ['Don Omar', 'The Last Don', 2003],
  ['Tego Calderón', 'El Abayarde', 2002],
  ['Wisin & Yandel', 'Pa’l Mundo', 2005],
  ['Calle 13', 'Residente o Visitante', 2007],
  ['Ivy Queen', 'Diva', 2003],
  ['Ozuna', 'Odisea', 2017],
  ['J Balvin', 'Energía', 2016],
  ['J Balvin', 'Colores', 2020],
  ['Bad Bunny', 'X 100pre', 2018],
  ['Bad Bunny', 'YHLQMDLG', 2020],
  ['Bad Bunny', 'Un Verano Sin Ti', 2022],
  ['Rosalía', 'El Mal Querer', 2018],
  ['Rosalía', 'Motomami', 2022],
  ['Karol G', 'Mañana Será Bonito', 2023],
  ['Anitta', 'Kisses', 2019],
  ['Peso Pluma', 'Génesis', 2023],
  ['Rauw Alejandro', 'Vice Versa', 2021],
  ['Feid', 'Ferxxo Vol. 2: Sagrado', 2023],

  // ---- Reggae / Dancehall ----
  ['Bob Marley & The Wailers', 'Catch a Fire', 1973],
  ['Bob Marley & The Wailers', 'Natty Dread', 1974],
  ['Peter Tosh', 'Legalize It', 1976],
  ['Burning Spear', 'Marcus Garvey', 1975],
  ['Toots and the Maytals', 'Funky Kingston', 1973],
  ['Jimmy Cliff', 'The Harder They Come', 1972],
  ['Black Uhuru', 'Red', 1981],
  ['Steel Pulse', 'Handsworth Revolution', 1978],
  ['Lee "Scratch" Perry', 'Super Ape', 1976],
  ['Buju Banton', "'Til Shiloh", 1995],
  ['Sean Paul', 'Dutty Rock', 2002],
  ['Shaggy', 'Hot Shot', 2000],
  ['Damian Marley', 'Welcome to Jamrock', 2005],
  ['Chronixx', 'Chronology', 2017],
  ['Protoje', 'Ancient Future', 2015],

  // ---- K-pop / J-pop ----
  ['BTS', 'Map of the Soul: 7', 2020],
  ['BTS', 'Love Yourself: Tear', 2018],
  ['BLACKPINK', 'The Album', 2020],
  ['TWICE', 'Formula of Love: O+T=<3', 2021],
  ['EXO', 'Exodus', 2015],
  ['Girls’ Generation', 'Oh!', 2010],
  ['Big Bang', 'Made', 2016],
  ['Stray Kids', 'Maxident', 2022],
  ['NewJeans', 'Get Up', 2023],
  ['Seventeen', 'FML', 2023],
  ['aespa', 'MY WORLD', 2023],
  ['Utada Hikaru', 'First Love', 1999],
  ['Perfume', 'Game', 2008],
  ['Yoasobi', 'The Book', 2021],

  // ---- Folk / Singer-songwriter ----
  ['Woody Guthrie', 'Dust Bowl Ballads', 1940],
  ['Pete Seeger', 'We Shall Overcome', 1963],
  ['Peter, Paul and Mary', "Peter, Paul and Mary", 1962],
  ['The Byrds', 'Mr. Tambourine Man', 1965],
  ['Simon & Garfunkel', 'Sounds of Silence', 1966],
  ['Leonard Cohen', 'Songs of Leonard Cohen', 1967],
  ['Nick Drake', 'Pink Moon', 1972],
  ['Cat Stevens', 'Tea for the Tillerman', 1970],
  ['James Taylor', 'Sweet Baby James', 1970],
  ['Carole King', 'Tapestry', 1971],
  ['Jackson Browne', 'Late for the Sky', 1974],
  ['Harry Chapin', 'Verities & Balderdash', 1974],
  ['John Prine', 'John Prine', 1971],
  ['Townes Van Zandt', 'Live at the Old Quarter', 1977],
  ['Gordon Lightfoot', 'Sundown', 1974],
  ['Tracy Chapman', 'New Beginning', 1995],
  ['Indigo Girls', 'Indigo Girls', 1989],
  ['Ani DiFranco', 'Little Plastic Castle', 1998],
  ['Jewel', 'Pieces of You', 1995],
  ['Sarah McLachlan', 'Fumbling Towards Ecstasy', 1993],
  ['Alanis Morissette', 'Supposed Former Infatuation Junkie', 1998],
  ['Fiona Apple', 'When the Pawn...', 1999],
  ['Fiona Apple', 'Fetch the Bolt Cutters', 2020],
  ['Iron & Wine', 'Our Endless Numbered Days', 2004],
  ['Sufjan Stevens', 'Carrie & Lowell', 2015],
  ['Bright Eyes', "I'm Wide Awake, It's Morning", 2005],
  ['Elliott Smith', 'Either/Or', 1997],
  ['Elliott Smith', 'XO', 1998],
  ['José González', 'Veneer', 2003],
  ['Damien Rice', 'O', 2002],
  ['Ray LaMontagne', 'Trouble', 2004],
  ['The Lumineers', 'The Lumineers', 2012],
  ['Mumford & Sons', 'Sigh No More', 2009],
  ['The Avett Brothers', 'Emotionalism', 2007],
  ['First Aid Kit', 'Stay Gold', 2014],
  ['Laura Marling', 'Once I Was an Eagle', 2013],
  ['Nick Cave and the Bad Seeds', 'The Boatman’s Call', 1997],
  ['Paul Simon', 'Graceland', 1986],
  ['Joan Baez', 'Diamonds & Rust', 1975],
  ['Tracy Chapman', 'Tracy Chapman', 1988],

  // ---- Blues ----
  ['Robert Johnson', 'King of the Delta Blues Singers', 1961],
  ['Muddy Waters', 'The Best of Muddy Waters', 1958],
  ['Howlin’ Wolf', 'Moanin’ in the Moonlight', 1959],
  ['B.B. King', 'Live at the Regal', 1965],
  ['Buddy Guy', 'A Man and the Blues', 1968],
  ['John Lee Hooker', 'The Healer', 1989],
  ['Albert King', 'Born Under a Bad Sign', 1967],
  ['Freddie King', 'Freddy King Sings', 1961],
  ['Etta James', 'At Last!', 1960],
  ['Stevie Ray Vaughan', 'Texas Flood', 1983],
  ['Stevie Ray Vaughan', 'Couldn’t Stand the Weather', 1984],
  ['Eric Clapton', 'Slowhand', 1977],
  ['John Mayall & The Bluesbreakers', 'Blues Breakers with Eric Clapton', 1966],
  ['Gary Clark Jr.', 'Blak and Blu', 2012],

  // ---- World / Afrobeats ----
  ['Fela Kuti', 'Expensive Shit', 1975],
  ['King Sunny Adé', 'Juju Music', 1982],
  ['Youssou N’Dour', 'The Guide (Wommat)', 1994],
  ['Salif Keita', 'Soro', 1987],
  ['Ali Farka Touré', 'Talking Timbuktu', 1994],
  ['Miriam Makeba', 'Miriam Makeba', 1960],
  ['Ladysmith Black Mambazo', 'Shaka Zulu', 1987],
  ['Manu Chao', 'Clandestino', 1998],
  ['Ravi Shankar', 'Live at Monterey', 1967],
  ['Buena Vista Social Club', 'Buena Vista Social Club', 1997],
  ['Burna Boy', 'African Giant', 2019],
  ['Burna Boy', 'Twice as Tall', 2020],
  ['Wizkid', 'Made in Lagos', 2020],
  ['Davido', 'A Good Time', 2019],
  ['Tems', 'Born in the Wild', 2024],
  ['Angélique Kidjo', 'Djin Djin', 2007],

  // ---- Christian / Gospel & Soundtracks / Musicals ----
  ['Mahalia Jackson', 'Gospels, Spirituals & Hymns', 1991],
  ['The Edwin Hawkins Singers', 'Let Us Go into the House of the Lord', 1969],
  ['Kirk Franklin', 'Kirk Franklin and the Family', 1993],
  ['Fred Hammond', 'Pages of Life: Chapters I & II', 1998],
  ['Amy Grant', 'Heart in Motion', 1991],
  ['MercyMe', 'Almost There', 2001],
  ['Hillsong United', 'Zion', 2013],
  ['Lauren Daigle', 'How Can It Be', 2015],
  ['Original Broadway Cast', 'Hamilton (Original Broadway Cast Recording)', 2015],
  ['Original Motion Picture Soundtrack', 'Purple Rain', 1984],
  ['Original Motion Picture Soundtrack', 'The Bodyguard', 1992],
  ['Original Motion Picture Soundtrack', 'Saturday Night Fever', 1977],
  ['Original Motion Picture Soundtrack', 'Guardians of the Galaxy: Awesome Mix Vol. 1', 2014],

  // ---- Hip-Hop / Rap: more depth (Southern, underground, drill, mixtape era) ----
  ['Three 6 Mafia', 'When the Smoke Clears: Sixty 6, Sixty 1', 2000],
  ['Lil Jon & the East Side Boyz', 'Kings of Crunk', 2002],
  ['Ying Yang Twins', "Me & My Brother", 2003],
  ['Bun B', 'Trill', 2005],
  ['Pimp C', 'Pimpalation', 2006],
  ['Z-Ro', 'Life', 2004],
  ['Devin the Dude', 'Just Tryin’ ta Live', 2002],
  ['Chamillionaire', 'The Sound of Revenge', 2005],
  ['Paul Wall', 'The Peoples Champ', 2005],
  ['Killer Mike', 'R.A.P. Music', 2012],
  ['El-P', 'Fantastic Damage', 2002],
  ['Aesop Rock', 'Labor Days', 2001],
  ['Cannibal Ox', 'The Cold Vein', 2001],
  ['Company Flow', 'Funcrusher Plus', 1997],
  ['Blackalicious', 'Blazing Arrow', 2002],
  ['People Under the Stairs', 'O.S.T.', 2002],
  ['Hieroglyphics', '3rd Eye Vision', 1998],
  ['Souls of Mischief', "93 'til Infinity", 1993],
  ['The Pharcyde', 'Bizarre Ride II the Pharcyde', 1992],
  ['Digable Planets', 'Reachin’ (A New Refutation of Time and Space)', 1993],
  ['Handsome Boy Modeling School', 'So... How’s Your Girl?', 1999],
  ['Gang Starr', 'Moment of Truth', 1998],
  ['Jeru the Damaja', 'The Sun Rises in the East', 1994],
  ['O.C.', 'Word...Life', 1994],
  ['Camp Lo', 'Uptown Saturday Night', 1997],
  ['Organized Konfusion', 'Stress: The Extinction Agenda', 1994],
  ['Del the Funky Homosapien', 'I Wish My Brother George Was Here', 1991],
  ['Kool Keith', 'Dr. Octagonecologyst', 1996],
  ['Non Phixion', 'The Future Is Now', 2002],
  ['Dead Prez', "Let's Get Free", 2000],
  ['The Coup', 'Party Music', 2001],
  ['Immortal Technique', 'Revolutionary Vol. 2', 2003],
  ['Brother Ali', 'Shadows on the Sun', 2003],
  ['Slug/Atmosphere', 'God Loves Ugly', 2002],
  ['Sage Francis', 'Personal Journals', 2002],
  ['MURS', 'Murs 3:16: The 9th Edition', 2004],
  ['Lecrae', 'Anomaly', 2014],
  ['NF', 'Perception', 2017],
  ['Logic', 'The Incredible True Story', 2015],
  ['Big K.R.I.T.', 'Live from the Underground', 2012],
  ['Curren$y', 'Pilot Talk', 2010],
  ['Wale', 'Ambition', 2011],
  ['Meek Mill', 'Dreams and Nightmares', 2012],
  ['French Montana', 'Excuse My French', 2013],
  ['Fabolous', 'Street Dreams', 2003],
  ['Juelz Santana', 'From Me to U', 2003],
  ['Young Buck', 'Straight Outta Cashville', 2004],
  ['Lloyd Banks', 'The Hunger for More', 2004],
  ['Tony Yayo', 'Thoughts of a Predicate Felon', 2005],
  ['Beanie Sigel', 'The Truth', 2000],
  ['State Property', 'State Property', 2002],
  ['Freeway', 'Philadelphia Freeway', 2003],
  ['Styles P', 'A Gangster and a Gentleman', 2002],
  ['The Lox', 'We Are the Streets', 2000],
  ['DJ Khaled', 'We the Best', 2007],
  ['DJ Quik', 'Quik Is the Name', 1991],
  ['MC Eiht', 'We Come Strapped', 1994],
  ['Above the Law', 'Livin’ Like Hustlers', 1990],
  ['Compton’s Most Wanted', 'Music to Driveby', 1992],
  ['Spice 1', 'Spice 1', 1992],
  ['E-40', 'In a Major Way', 1995],
  ['Too $hort', 'Life Is... Too Short', 1988],
  ['Digital Underground', 'Sex Packets', 1990],
  ['Souls of Mischief', 'No Man’s Land', 1995],
  ['Kurupt', 'Kuruption!', 1998],
  ['Tha Dogg Pound', 'Dogg Food', 1995],
  ['Xzibit', 'Restless', 2000],
  ['Ras Kass', 'Soul on Ice', 1996],
  ['Fashawn', 'Boy Meets World', 2009],
  ['Skyzoo', 'The Salvation', 2009],
  ['Roc Marciano', 'Marcberg', 2010],
  ['Westside Gunn', 'Pray for Paris', 2020],
  ['Griselda/Benny the Butcher', 'Burden of Proof', 2020],
  ['Conway the Machine', "God Don't Make Mistakes", 2022],
  ['Mach-Hommy', 'Pray for Haiti', 2021],
  ['Wiki', 'Half God', 2021],
  ['MIKE', 'Weight of the World', 2021],
  ['Navy Blue', 'Song of Sage: Post Panic!', 2020],
  ['Chief Keef', 'Finally Rich', 2012],
  ['Lil Durk', 'Signed to the Streets', 2013],
  ['G Herbo', 'Humble Beast', 2017],
  ['Polo G', 'The Goat', 2020],
  ['Lil Baby', 'My Turn', 2020],
  ['DaBaby', 'Kirk', 2019],
  ['NLE Choppa', 'Top Shotta', 2020],
  ['Central Cee', '23', 2021],
  ['Headie One', 'Edna', 2020],
  ['AJ Tracey', 'AJ Tracey', 2019],
  ['Slowthai', 'Nothing Great About Britain', 2019],
  ['Ice Spice', 'Like..?', 2023],
  ['GloRilla', 'Ehhthang Ehhthang', 2022],
  ['Latto', '777', 2022],
  ['Flo Milli', 'Ho, Why Is You Here?', 2020],
  ['Doechii', 'Alligator Bites Never Heal', 2024],
  ['Tierra Whack', 'Whack World', 2018],
  ['Rapsody', 'Eve', 2019],
  ['Smino', 'Blkswn', 2017],
  ['Saba', 'Care for Me', 2018],
  ['Mick Jenkins', 'The Water[s]', 2014],
  ['Joey Bada$$', "1999", 2012],
  ['Joey Bada$$', 'B4.DA.$$', 2015],
  ['Pro Era/CJ Fly', 'Thee Way Eye See It', 2015],
  ['Flatbush Zombies', '3001: A Laced Odyssey', 2016],
  ['The Underachievers', 'Indigoism', 2013],
  ['Kid Cudi', 'Man on the Moon: The End of Day', 2009],
  ['Kid Cudi', 'Man on the Moon II: The Legend of Mr. Rager', 2010],
  ['Big Sean', 'Dark Sky Paradise', 2015],
  ['Pusha T', 'Daytona', 2018],
  ['Pusha T', 'It’s Almost Dry', 2022],

  // ---- Funk / Disco ----
  ['James Brown', 'The Payback', 1973],
  ['Parliament', 'Mothership Connection', 1975],
  ['Funkadelic', 'One Nation Under a Groove', 1978],
  ['Bootsy Collins', 'Ahh... The Name Is Bootsy, Baby!', 1977],
  ['Sly and the Family Stone', 'Stand!', 1969],
  ['War', 'The World Is a Ghetto', 1972],
  ['Kool & the Gang', 'Wild and Peaceful', 1973],
  ['The Ohio Players', 'Honey', 1975],
  ['Rick James', 'Street Songs', 1981],
  ['Zapp', 'Zapp', 1980],
  ['Donna Summer', 'Bad Girls', 1979],
  ['Gloria Gaynor', 'Love Tracks', 1978],
  ['The Bee Gees', 'Children of the World', 1976],
  ['KC and the Sunshine Band', "KC and the Sunshine Band", 1975],
  ['Diana Ross', 'diana', 1980],
  ['Michael Jackson', 'Off the Wall', 1979],
  ['Cameo', 'Word Up!', 1986],
  ['The Gap Band', 'Gap Band IV', 1982],
  ['Chic', 'Risqué', 1979],

  // ---- Classical / Instrumental ----
  ['Ludwig van Beethoven', 'Symphony No. 9', 1824],
  ['Wolfgang Amadeus Mozart', 'Requiem', 1791],
  ['Johann Sebastian Bach', 'The Well-Tempered Clavier', 1722],
  ['Antonio Vivaldi', 'The Four Seasons', 1725],
  ['Igor Stravinsky', 'The Rite of Spring', 1913],
  ['Sergei Rachmaninoff', 'Piano Concerto No. 2', 1901],
  ['Claude Debussy', 'Clair de Lune (Suite Bergamasque)', 1905],
  ['Gustav Holst', 'The Planets', 1918],
  ['George Gershwin', 'Rhapsody in Blue', 1924],
  ['Aaron Copland', 'Appalachian Spring', 1944],
  ['Philip Glass', 'Glassworks', 1982],
  ['Steve Reich', 'Music for 18 Musicians', 1978],
  ['Max Richter', 'The Blue Notebooks', 2004],
  ['Ólafur Arnalds', 'Living Room Songs', 2013],
  ['Ludovico Einaudi', 'Divenire', 2006],
  ['Hans Zimmer', 'Interstellar (Original Motion Picture Soundtrack)', 2014],
  ['Yo-Yo Ma', 'Bach: The Cello Suites', 1983],
  ['John Williams', 'Star Wars: A New Hope (Original Motion Picture Soundtrack)', 1977],
  ['Ennio Morricone', 'The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)', 1966],
  ['Joe Hisaishi', 'Spirited Away (Soundtrack)', 2001],

  // ---- More punk / hardcore / emo ----
  ['The Clash', 'Give ’Em Enough Rope', 1978],
  ['X-Ray Spex', 'Germfree Adolescents', 1978],
  ['The Damned', 'Damned Damned Damned', 1977],
  ['Social Distortion', 'Social Distortion', 1990],
  ['Bad Religion', 'Suffer', 1988],
  ['NOFX', 'Punk in Drublic', 1994],
  ['Rancid', "...And Out Come the Wolves", 1995],
  ['Green Day', 'American Idiot', 2004],
  ['Blink-182', 'Enema of the State', 1999],
  ['Sum 41', 'All Killer No Filler', 2001],
  ['Good Charlotte', 'The Young and the Hopeless', 2002],
  ['Fall Out Boy', "From Under the Cork Tree", 2005],
  ['Paramore', 'Riot!', 2007],
  ['Paramore', 'After Laughter', 2017],
  ['My Chemical Romance', 'Three Cheers for Sweet Revenge', 2004],
  ['Panic! at the Disco', 'A Fever You Can’t Sweat Out', 2005],
  ['Jimmy Eat World', 'Clarity', 1999],
  ['The Get Up Kids', 'Something to Write Home About', 1999],
  ['Brand New', 'The Devil and God Are Raging Inside Me', 2006],
  ['Taking Back Sunday', 'Tell All Your Friends', 2002],
  ['Thursday', 'Full Collapse', 2001],
  ['At the Drive-In', 'Relationship of Command', 2000],
  ['Refused', 'The Shape of Punk to Come', 1998],
  ['Rage Against the Machine', 'The Battle of Los Angeles', 1999],
  ['Descendents', 'Milo Goes to College', 1982],
  ['Operation Ivy', 'Energy', 1989],
  ['Circle Jerks', 'Group Sex', 1980],
  ['Suicidal Tendencies', 'Suicidal Tendencies', 1983],
  ['Anti-Flag', 'The Terror State', 2003],
  ['Against Me!', 'Transgender Dysphoria Blues', 2014],
  ['Title Fight', 'Hyperview', 2015],
  ['La Dispute', 'Wildlife', 2011],

  // ---- More 2020s indie / alternative / pop ----
  ['Wet Leg', 'Wet Leg', 2022],
  ['Black Country, New Road', 'Ants From Up There', 2022],
  ['black midi', 'Cavalcade', 2021],
  ['Squid', 'Bright Green Field', 2021],
  ['Yard Act', 'The Overload', 2022],
  ['Alvvays', 'Antisocialites', 2017],
  ['Beach House', 'Teen Dream', 2010],
  ['Beach House', 'Depression Cherry', 2015],
  ['Beach Bunny', 'Honeymoon', 2020],
  ['Snail Mail', 'Lush', 2018],
  ['Soccer Mommy', 'Color Theory', 2020],
  ['Japanese Breakfast', 'Jubilee', 2021],
  ['Mitski', 'Be the Cowboy', 2018],
  ['Mitski', 'Puberty 2', 2016],
  ['Waxahatchee', 'Saint Cloud', 2020],
  ['Julien Baker', 'Turn Out the Lights', 2017],
  ['Lucy Dacus', 'Home Video', 2021],
  ['Faye Webster', 'I Know I’m Funny haha', 2021],
  ['Clairo', 'Immunity', 2019],
  ['girl in red', 'if i could make it go quiet', 2021],
  ['Beabadoobee', 'Fake It Flowers', 2020],
  ['Rex Orange County', 'Pony', 2019],
  ['Cuco', 'Para Mi', 2019],
  ['Steve Lacy', 'Gemini Rights', 2022],
  ['Omar Apollo', 'Ivory', 2022],
  ['Ethel Cain', 'Preacher’s Daughter', 2022],
  ['MJ Lenderman', 'Boat Songs', 2022],
  ['Alex G', 'House of Sugar', 2019],
  ['Men I Trust', 'Oncle Jazz', 2019],
];

module.exports = buildOptions(RAW_ALBUMS);
