const { buildOptions } = require('./build-options');

// Curated list of widely-recognized films spanning eras and genres, used as the fixed
// option set for the "Greatest Movie of All Time" poll.
// Tuples are [director, title, year].
const RAW_MOVIES = [
  ['Victor Fleming', 'The Wizard of Oz', 1939],
  ['Victor Fleming', 'Gone with the Wind', 1939],
  ['Orson Welles', 'Citizen Kane', 1941],
  ['Michael Curtiz', 'Casablanca', 1942],
  ['Gene Kelly, Stanley Donen', 'Singin’ in the Rain', 1952],
  ['Billy Wilder', 'Sunset Boulevard', 1950],
  ['Alfred Hitchcock', 'Rear Window', 1954],
  ['Sidney Lumet', '12 Angry Men', 1957],
  ['Alfred Hitchcock', 'Vertigo', 1958],
  ['Billy Wilder', 'Some Like It Hot', 1959],
  ['Alfred Hitchcock', 'North by Northwest', 1959],
  ['Alfred Hitchcock', 'Psycho', 1960],
  ['David Lean', 'Lawrence of Arabia', 1962],
  ['Robert Mulligan', 'To Kill a Mockingbird', 1962],
  ['Stanley Kubrick', 'Dr. Strangelove', 1964],
  ['Stanley Kubrick', '2001: A Space Odyssey', 1968],
  ['Mike Nichols', 'The Graduate', 1967],
  ['Arthur Penn', 'Bonnie and Clyde', 1967],
  ['Dennis Hopper', 'Easy Rider', 1969],
  ['Francis Ford Coppola', 'The Godfather', 1972],
  ['Francis Ford Coppola', 'The Godfather Part II', 1974],
  ['Roman Polanski', 'Chinatown', 1974],
  ['Steven Spielberg', 'Jaws', 1975],
  ['Milos Forman', 'One Flew Over the Cuckoo’s Nest', 1975],
  ['Martin Scorsese', 'Taxi Driver', 1976],
  ['John G. Avildsen', 'Rocky', 1976],
  ['George Lucas', 'Star Wars', 1977],
  ['Woody Allen', 'Annie Hall', 1977],
  ['Michael Cimino', 'The Deer Hunter', 1978],
  ['Francis Ford Coppola', 'Apocalypse Now', 1979],
  ['Ridley Scott', 'Alien', 1979],
  ['Stanley Kubrick', 'The Shining', 1980],
  ['Irvin Kershner', 'The Empire Strikes Back', 1980],
  ['Steven Spielberg', 'Raiders of the Lost Ark', 1981],
  ['Steven Spielberg', 'E.T. the Extra-Terrestrial', 1982],
  ['Ridley Scott', 'Blade Runner', 1982],
  ['Richard Marquand', 'Return of the Jedi', 1983],
  ['Ivan Reitman', 'Ghostbusters', 1984],
  ['Robert Zemeckis', 'Back to the Future', 1985],
  ['John Hughes', 'The Breakfast Club', 1985],
  ['Oliver Stone', 'Platoon', 1986],
  ['James Cameron', 'Aliens', 1986],
  ['Tony Scott', 'Top Gun', 1986],
  ['Stanley Kubrick', 'Full Metal Jacket', 1987],
  ['Rob Reiner', 'The Princess Bride', 1987],
  ['John McTiernan', 'Die Hard', 1988],
  ['Spike Lee', 'Do the Right Thing', 1989],
  ['Tim Burton', 'Batman', 1989],
  ['Rob Reiner', 'When Harry Met Sally…', 1989],
  ['Martin Scorsese', 'Goodfellas', 1990],
  ['James Cameron', 'Terminator 2: Judgment Day', 1991],
  ['Jonathan Demme', 'The Silence of the Lambs', 1991],
  ['Gary Trousdale, Kirk Wise', 'Beauty and the Beast', 1991],
  ['Clint Eastwood', 'Unforgiven', 1992],
  ['Steven Spielberg', 'Jurassic Park', 1993],
  ['Steven Spielberg', 'Schindler’s List', 1993],
  ['Frank Darabont', 'The Shawshank Redemption', 1994],
  ['Quentin Tarantino', 'Pulp Fiction', 1994],
  ['Robert Zemeckis', 'Forrest Gump', 1994],
  ['Roger Allers, Rob Minkoff', 'The Lion King', 1994],
  ['David Fincher', 'Se7en', 1995],
  ['Bryan Singer', 'The Usual Suspects', 1995],
  ['John Lasseter', 'Toy Story', 1995],
  ['Mel Gibson', 'Braveheart', 1995],
  ['Joel Coen', 'Fargo', 1996],
  ['Danny Boyle', 'Trainspotting', 1996],
  ['James Cameron', 'Titanic', 1997],
  ['Gus Van Sant', 'Good Will Hunting', 1997],
  ['Curtis Hanson', 'L.A. Confidential', 1997],
  ['Joel Coen', 'The Big Lebowski', 1998],
  ['Steven Spielberg', 'Saving Private Ryan', 1998],
  ['Lana Wachowski, Lilly Wachowski', 'The Matrix', 1999],
  ['David Fincher', 'Fight Club', 1999],
  ['Sam Mendes', 'American Beauty', 1999],
  ['M. Night Shyamalan', 'The Sixth Sense', 1999],
  ['Spike Jonze', 'Being John Malkovich', 1999],
  ['Ridley Scott', 'Gladiator', 2000],
  ['Christopher Nolan', 'Memento', 2000],
  ['Ang Lee', 'Crouching Tiger, Hidden Dragon', 2000],
  ['Peter Jackson', 'The Lord of the Rings: The Fellowship of the Ring', 2001],
  ['Peter Jackson', 'The Lord of the Rings: The Two Towers', 2002],
  ['Peter Jackson', 'The Lord of the Rings: The Return of the King', 2003],
  ['Hayao Miyazaki', 'Spirited Away', 2001],
  ['Jean-Pierre Jeunet', 'Amélie', 2001],
  ['Fernando Meirelles', 'City of God', 2002],
  ['Quentin Tarantino', 'Kill Bill: Vol. 1', 2003],
  ['Michel Gondry', 'Eternal Sunshine of the Spotless Mind', 2004],
  ['Guillermo del Toro', 'Pan’s Labyrinth', 2006],
  ['Martin Scorsese', 'The Departed', 2006],
  ['Joel Coen, Ethan Coen', 'No Country for Old Men', 2007],
  ['Paul Thomas Anderson', 'There Will Be Blood', 2007],
  ['Christopher Nolan', 'The Dark Knight', 2008],
  ['Andrew Stanton', 'WALL-E', 2008],
  ['Danny Boyle', 'Slumdog Millionaire', 2008],
  ['Pete Docter', 'Up', 2009],
  ['Quentin Tarantino', 'Inglourious Basterds', 2009],
  ['James Cameron', 'Avatar', 2009],
  ['Christopher Nolan', 'Inception', 2010],
  ['David Fincher', 'The Social Network', 2010],
  ['Lee Unkrich', 'Toy Story 3', 2010],
  ['Nicolas Winding Refn', 'Drive', 2011],
  ['Damien Chazelle', 'Whiplash', 2014],
  ['Wes Anderson', 'The Grand Budapest Hotel', 2014],
  ['George Miller', 'Mad Max: Fury Road', 2015],
  ['Tom McCarthy', 'Spotlight', 2015],
  ['Damien Chazelle', 'La La Land', 2016],
  ['Barry Jenkins', 'Moonlight', 2016],
  ['Denis Villeneuve', 'Arrival', 2016],
  ['Jordan Peele', 'Get Out', 2017],
  ['Greta Gerwig', 'Lady Bird', 2017],
  ['Guillermo del Toro', 'The Shape of Water', 2017],
  ['Denis Villeneuve', 'Blade Runner 2049', 2017],
  ['Bong Joon-ho', 'Parasite', 2019],
  ['Todd Phillips', 'Joker', 2019],
  ['Quentin Tarantino', 'Once Upon a Time in Hollywood', 2019],
  ['Anthony Russo, Joe Russo', 'Avengers: Endgame', 2019],
  ['Rian Johnson', 'Knives Out', 2019],
  ['Sam Mendes', '1917', 2019],
  ['Chloé Zhao', 'Nomadland', 2020],
  ['Denis Villeneuve', 'Dune', 2021],
  ['Daniel Kwan, Daniel Scheinert', 'Everything Everywhere All at Once', 2022],
  ['Joseph Kosinski', 'Top Gun: Maverick', 2022],
  ['Martin McDonagh', 'The Banshees of Inisherin', 2022],
  ['Christopher Nolan', 'Oppenheimer', 2023],
  ['Greta Gerwig', 'Barbie', 2023],
  ['Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', 'Spider-Man: Across the Spider-Verse', 2023],
  ['Yorgos Lanthimos', 'Poor Things', 2023],
  ['Denis Villeneuve', 'Dune: Part Two', 2024],
];

module.exports = buildOptions(RAW_MOVIES);
