const { buildOptions } = require('./build-options');

// Curated list of widely-recognized films spanning eras and genres, used as the fixed
// option set for the "Greatest Movie of All Time" poll.
// Tuples are [director, title, year].
const RAW_MOVIES = [
  ['Victor Fleming', 'The Wizard of Oz', 1939],
  ['Victor Fleming', 'Gone with the Wind', 1939],
  ['Orson Welles', 'Citizen Kane', 1941],
  ['Michael Curtiz', 'Casablanca', 1942],
  ['Gene Kelly, Stanley Donen', 'Singin’ in the Rain', 1952],
  ['Billy Wilder', 'Sunset Boulevard', 1950],
  ['Alfred Hitchcock', 'Rear Window', 1954],
  ['Sidney Lumet', '12 Angry Men', 1957],
  ['Alfred Hitchcock', 'Vertigo', 1958],
  ['Billy Wilder', 'Some Like It Hot', 1959],
  ['Alfred Hitchcock', 'North by Northwest', 1959],
  ['Alfred Hitchcock', 'Psycho', 1960],
  ['David Lean', 'Lawrence of Arabia', 1962],
  ['Robert Mulligan', 'To Kill a Mockingbird', 1962],
  ['Stanley Kubrick', 'Dr. Strangelove', 1964],
  ['Stanley Kubrick', '2001: A Space Odyssey', 1968],
  ['Mike Nichols', 'The Graduate', 1967],
  ['Arthur Penn', 'Bonnie and Clyde', 1967],
  ['Dennis Hopper', 'Easy Rider', 1969],
  ['Francis Ford Coppola', 'The Godfather', 1972],
  ['Francis Ford Coppola', 'The Godfather Part II', 1974],
  ['Roman Polanski', 'Chinatown', 1974],
  ['Steven Spielberg', 'Jaws', 1975],
  ['Milos Forman', 'One Flew Over the Cuckoo’s Nest', 1975],
  ['Martin Scorsese', 'Taxi Driver', 1976],
  ['John G. Avildsen', 'Rocky', 1976],
  ['George Lucas', 'Star Wars', 1977],
  ['Woody Allen', 'Annie Hall', 1977],
  ['Michael Cimino', 'The Deer Hunter', 1978],
  ['Francis Ford Coppola', 'Apocalypse Now', 1979],
  ['Ridley Scott', 'Alien', 1979],
  ['Stanley Kubrick', 'The Shining', 1980],
  ['Irvin Kershner', 'The Empire Strikes Back', 1980],
  ['Steven Spielberg', 'Raiders of the Lost Ark', 1981],
  ['Steven Spielberg', 'E.T. the Extra-Terrestrial', 1982],
  ['Ridley Scott', 'Blade Runner', 1982],
  ['Richard Marquand', 'Return of the Jedi', 1983],
  ['Ivan Reitman', 'Ghostbusters', 1984],
  ['Robert Zemeckis', 'Back to the Future', 1985],
  ['John Hughes', 'The Breakfast Club', 1985],
  ['Oliver Stone', 'Platoon', 1986],
  ['James Cameron', 'Aliens', 1986],
  ['Tony Scott', 'Top Gun', 1986],
  ['Stanley Kubrick', 'Full Metal Jacket', 1987],
  ['Rob Reiner', 'The Princess Bride', 1987],
  ['John McTiernan', 'Die Hard', 1988],
  ['Spike Lee', 'Do the Right Thing', 1989],
  ['Tim Burton', 'Batman', 1989],
  ['Rob Reiner', 'When Harry Met Sally…', 1989],
  ['Martin Scorsese', 'Goodfellas', 1990],
  ['James Cameron', 'Terminator 2: Judgment Day', 1991],
  ['Jonathan Demme', 'The Silence of the Lambs', 1991],
  ['Gary Trousdale, Kirk Wise', 'Beauty and the Beast', 1991],
  ['Clint Eastwood', 'Unforgiven', 1992],
  ['Steven Spielberg', 'Jurassic Park', 1993],
  ['Steven Spielberg', 'Schindler’s List', 1993],
  ['Frank Darabont', 'The Shawshank Redemption', 1994],
  ['Quentin Tarantino', 'Pulp Fiction', 1994],
  ['Robert Zemeckis', 'Forrest Gump', 1994],
  ['Roger Allers, Rob Minkoff', 'The Lion King', 1994],
  ['David Fincher', 'Se7en', 1995],
  ['Bryan Singer', 'The Usual Suspects', 1995],
  ['John Lasseter', 'Toy Story', 1995],
  ['Mel Gibson', 'Braveheart', 1995],
  ['Joel Coen', 'Fargo', 1996],
  ['Danny Boyle', 'Trainspotting', 1996],
  ['James Cameron', 'Titanic', 1997],
  ['Gus Van Sant', 'Good Will Hunting', 1997],
  ['Curtis Hanson', 'L.A. Confidential', 1997],
  ['Joel Coen', 'The Big Lebowski', 1998],
  ['Steven Spielberg', 'Saving Private Ryan', 1998],
  ['Lana Wachowski, Lilly Wachowski', 'The Matrix', 1999],
  ['David Fincher', 'Fight Club', 1999],
  ['Sam Mendes', 'American Beauty', 1999],
  ['M. Night Shyamalan', 'The Sixth Sense', 1999],
  ['Spike Jonze', 'Being John Malkovich', 1999],
  ['Ridley Scott', 'Gladiator', 2000],
  ['Christopher Nolan', 'Memento', 2000],
  ['Ang Lee', 'Crouching Tiger, Hidden Dragon', 2000],
  ['Peter Jackson', 'The Lord of the Rings: The Fellowship of the Ring', 2001],
  ['Peter Jackson', 'The Lord of the Rings: The Two Towers', 2002],
  ['Peter Jackson', 'The Lord of the Rings: The Return of the King', 2003],
  ['Hayao Miyazaki', 'Spirited Away', 2001],
  ['Jean-Pierre Jeunet', 'Amélie', 2001],
  ['Fernando Meirelles', 'City of God', 2002],
  ['Quentin Tarantino', 'Kill Bill: Vol. 1', 2003],
  ['Michel Gondry', 'Eternal Sunshine of the Spotless Mind', 2004],
  ['Guillermo del Toro', 'Pan’s Labyrinth', 2006],
  ['Martin Scorsese', 'The Departed', 2006],
  ['Joel Coen, Ethan Coen', 'No Country for Old Men', 2007],
  ['Paul Thomas Anderson', 'There Will Be Blood', 2007],
  ['Christopher Nolan', 'The Dark Knight', 2008],
  ['Andrew Stanton', 'WALL-E', 2008],
  ['Danny Boyle', 'Slumdog Millionaire', 2008],
  ['Pete Docter', 'Up', 2009],
  ['Quentin Tarantino', 'Inglourious Basterds', 2009],
  ['James Cameron', 'Avatar', 2009],
  ['Christopher Nolan', 'Inception', 2010],
  ['David Fincher', 'The Social Network', 2010],
  ['Lee Unkrich', 'Toy Story 3', 2010],
  ['Nicolas Winding Refn', 'Drive', 2011],
  ['Damien Chazelle', 'Whiplash', 2014],
  ['Wes Anderson', 'The Grand Budapest Hotel', 2014],
  ['George Miller', 'Mad Max: Fury Road', 2015],
  ['Tom McCarthy', 'Spotlight', 2015],
  ['Damien Chazelle', 'La La Land', 2016],
  ['Barry Jenkins', 'Moonlight', 2016],
  ['Denis Villeneuve', 'Arrival', 2016],
  ['Jordan Peele', 'Get Out', 2017],
  ['Greta Gerwig', 'Lady Bird', 2017],
  ['Guillermo del Toro', 'The Shape of Water', 2017],
  ['Denis Villeneuve', 'Blade Runner 2049', 2017],
  ['Bong Joon-ho', 'Parasite', 2019],
  ['Todd Phillips', 'Joker', 2019],
  ['Quentin Tarantino', 'Once Upon a Time in Hollywood', 2019],
  ['Anthony Russo, Joe Russo', 'Avengers: Endgame', 2019],
  ['Rian Johnson', 'Knives Out', 2019],
  ['Sam Mendes', '1917', 2019],
  ['Chloé Zhao', 'Nomadland', 2020],
  ['Denis Villeneuve', 'Dune', 2021],
  ['Daniel Kwan, Daniel Scheinert', 'Everything Everywhere All at Once', 2022],
  ['Joseph Kosinski', 'Top Gun: Maverick', 2022],
  ['Martin McDonagh', 'The Banshees of Inisherin', 2022],
  ['Christopher Nolan', 'Oppenheimer', 2023],
  ['Greta Gerwig', 'Barbie', 2023],
  ['Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', 'Spider-Man: Across the Spider-Verse', 2023],
  ['Yorgos Lanthimos', 'Poor Things', 2023],
  ['Denis Villeneuve', 'Dune: Part Two', 2024],

  // --- Silent & early classics ---
  ['Georges Méliès', 'A Trip to the Moon', 1902],
  ['D.W. Griffith', 'Intolerance', 1916],
  ['Robert Wiene', 'The Cabinet of Dr. Caligari', 1920],
  ['F.W. Murnau', 'Nosferatu', 1922],
  ['Sergei Eisenstein', 'Battleship Potemkin', 1925],
  ['Fritz Lang', 'Metropolis', 1927],
  ['Charlie Chaplin', 'The Gold Rush', 1925],
  ['Charlie Chaplin', 'City Lights', 1931],
  ['Charlie Chaplin', 'Modern Times', 1936],
  ['Charlie Chaplin', 'The Great Dictator', 1940],
  ['Buster Keaton', 'The General', 1926],
  ['Carl Theodor Dreyer', 'The Passion of Joan of Arc', 1928],
  ['Jean Renoir', 'Grand Illusion', 1937],
  ['Jean Renoir', 'The Rules of the Game', 1939],

  // --- Golden age & foreign classics ---
  ['Akira Kurosawa', 'Rashomon', 1950],
  ['Akira Kurosawa', 'Seven Samurai', 1954],
  ['Akira Kurosawa', 'Ikiru', 1952],
  ['Akira Kurosawa', 'Yojimbo', 1961],
  ['Akira Kurosawa', 'Ran', 1985],
  ['Yasujirō Ozu', 'Tokyo Story', 1953],
  ['Kenji Mizoguchi', 'Ugetsu', 1953],
  ['Federico Fellini', 'La Strada', 1954],
  ['Federico Fellini', 'La Dolce Vita', 1960],
  ['Federico Fellini', '8½', 1963],
  ['Vittorio De Sica', 'Bicycle Thieves', 1948],
  ['Ingmar Bergman', 'The Seventh Seal', 1957],
  ['Ingmar Bergman', 'Wild Strawberries', 1957],
  ['Ingmar Bergman', 'Persona', 1966],
  ['Jean-Luc Godard', 'Breathless', 1960],
  ['François Truffaut', 'The 400 Blows', 1959],
  ['François Truffaut', 'Jules and Jim', 1962],
  ['Agnès Varda', 'Cléo from 5 to 7', 1962],
  ['Michelangelo Antonioni', "L'Avventura", 1960],
  ['Luis Buñuel', 'The Discreet Charm of the Bourgeoisie', 1972],
  ['Satyajit Ray', 'Pather Panchali', 1955],
  ['Andrei Tarkovsky', 'Andrei Rublev', 1966],
  ['Andrei Tarkovsky', 'Solaris', 1972],
  ['Andrei Tarkovsky', 'Stalker', 1979],
  ['Sergio Leone', 'The Good, the Bad and the Ugly', 1966],
  ['Sergio Leone', 'Once Upon a Time in the West', 1968],
  ['Sergio Leone', 'Once Upon a Time in America', 1984],
  ['Jacques Demy', 'The Umbrellas of Cherbourg', 1964],
  ['Robert Wise, Jerome Robbins', 'West Side Story', 1961],
  ['Robert Wise', 'The Sound of Music', 1965],

  // --- 70s-90s expanded ---
  ['William Friedkin', 'The Exorcist', 1973],
  ['William Friedkin', 'The French Connection', 1971],
  ['Sidney Lumet', 'Network', 1976],
  ['Sidney Lumet', 'Dog Day Afternoon', 1975],
  ['Alan J. Pakula', 'All the President\'s Men', 1976],
  ['Hal Ashby', 'Being There', 1979],
  ['Terrence Malick', 'Days of Heaven', 1978],
  ['Terrence Malick', 'Badlands', 1973],
  ['Terrence Malick', 'The Thin Red Line', 1998],
  ['Ridley Scott', 'Thelma & Louise', 1991],
  ['Barry Levinson', 'Rain Man', 1988],
  ['Lawrence Kasdan', 'The Big Chill', 1983],
  ['James L. Brooks', 'Terms of Endearment', 1983],
  ['Robert Redford', 'Ordinary People', 1980],
  ['Warren Beatty', 'Reds', 1981],
  ['Richard Attenborough', 'Gandhi', 1982],
  ['Bernardo Bertolucci', 'The Last Emperor', 1987],
  ['Peter Weir', 'Dead Poets Society', 1989],
  ['Peter Weir', 'The Truman Show', 1998],
  ['Peter Weir', 'Witness', 1985],
  ['Adrian Lyne', 'Fatal Attraction', 1987],
  ['James Brooks', 'Broadcast News', 1987],
  ['John Carpenter', 'Halloween', 1978],
  ['John Carpenter', 'The Thing', 1982],
  ['John Carpenter', 'Escape from New York', 1981],
  ['Tobe Hooper', 'The Texas Chain Saw Massacre', 1974],
  ['Wes Craven', 'A Nightmare on Elm Street', 1984],
  ['Wes Craven', 'Scream', 1996],
  ['Sean S. Cunningham', 'Friday the 13th', 1980],
  ['George A. Romero', 'Night of the Living Dead', 1968],
  ['George A. Romero', 'Dawn of the Dead', 1978],
  ['David Cronenberg', 'The Fly', 1986],
  ['David Cronenberg', 'Videodrome', 1983],
  ['David Lynch', 'Blue Velvet', 1986],
  ['David Lynch', 'Mulholland Drive', 2001],
  ['David Lynch', 'Eraserhead', 1977],
  ['Terry Gilliam', 'Brazil', 1985],
  ['Terry Gilliam', '12 Monkeys', 1995],
  ['Terry Jones, Terry Gilliam', 'Monty Python and the Holy Grail', 1975],
  ['Terry Jones', 'Life of Brian', 1979],
  ['John Landis', 'The Blues Brothers', 1980],
  ['John Landis', 'An American Werewolf in London', 1981],
  ['Harold Ramis', 'Groundhog Day', 1993],
  ['Harold Ramis', 'Caddyshack', 1980],
  ['Amy Heckerling', 'Fast Times at Ridgemont High', 1982],
  ['Cameron Crowe', 'Say Anything…', 1989],
  ['Cameron Crowe', 'Almost Famous', 2000],
  ['Penny Marshall', 'Big', 1988],
  ['Penny Marshall', 'A League of Their Own', 1992],
  ['Chris Columbus', 'Home Alone', 1990],
  ['Robert Zemeckis', 'Who Framed Roger Rabbit', 1988],
  ['Robert Zemeckis', 'Cast Away', 2000],
  ['Robert Zemeckis', 'Back to the Future Part II', 1989],
  ['George Miller', 'Mad Max 2: The Road Warrior', 1981],
  ['George Miller', 'Babe', 1995],
  ['Paul Verhoeven', 'RoboCop', 1987],
  ['Paul Verhoeven', 'Total Recall', 1990],
  ['Paul Verhoeven', 'Starship Troopers', 1997],
  ['James Cameron', 'The Terminator', 1984],
  ['James Cameron', 'True Lies', 1994],
  ['Jonathan Demme', 'Philadelphia', 1993],
  ['Jonathan Demme', 'Stop Making Sense', 1984],
  ['Barry Sonnenfeld', 'Men in Black', 1997],
  ['Ivan Reitman', 'Twins', 1988],
  ['Ron Howard', 'Apollo 13', 1995],
  ['Ron Howard', 'A Beautiful Mind', 2001],
  ['Ron Howard', 'Splash', 1984],
  ['Rob Reiner', 'Stand by Me', 1986],
  ['Rob Reiner', 'Misery', 1990],
  ['Nora Ephron', 'Sleepless in Seattle', 1993],
  ['Nora Ephron', "You've Got Mail", 1998],
  ['Garry Marshall', 'Pretty Woman', 1990],
  ['Adrian Lyne', 'Flashdance', 1983],
  ['Herbert Ross', 'Footloose', 1984],
  ['Alan Parker', 'Fame', 1980],
  ['Alan Parker', 'The Commitments', 1991],
  ['Alan Parker', 'Mississippi Burning', 1988],
  ['Milos Forman', 'Amadeus', 1984],
  ['Oliver Stone', 'JFK', 1991],
  ['Oliver Stone', 'Wall Street', 1987],
  ['Oliver Stone', 'Born on the Fourth of July', 1989],
  ['Kevin Costner', 'Dances with Wolves', 1990],
  ['Jonathan Demme', 'Married to the Mob', 1988],
  ['Bille August', 'Pelle the Conqueror', 1987],
  ['Steven Spielberg', 'Close Encounters of the Third Kind', 1977],
  ['Steven Spielberg', 'Hook', 1991],
  ['Steven Spielberg', 'Empire of the Sun', 1987],
  ['Steven Spielberg', 'Minority Report', 2002],
  ['Steven Spielberg', 'Catch Me If You Can', 2002],
  ['Steven Spielberg', 'Munich', 2005],
  ['Steven Spielberg', 'Lincoln', 2012],
  ['Steven Spielberg', 'Bridge of Spies', 2015],
  ['Steven Spielberg', 'The Fabelmans', 2022],
  ['George Lucas', 'American Graffiti', 1973],
  ['George Lucas', 'Star Wars: Episode I – The Phantom Menace', 1999],
  ['George Lucas', 'Star Wars: Episode III – Revenge of the Sith', 2005],
  ['Irvin Kershner, George Lucas', 'Star Wars: Episode II – Attack of the Clones', 2002],
  ['J.J. Abrams', 'Star Wars: The Force Awakens', 2015],
  ['Rian Johnson', 'Star Wars: The Last Jedi', 2017],
  ['Gareth Edwards', 'Rogue One: A Star Wars Story', 2016],
  ['Chris Columbus', "Harry Potter and the Sorcerer's Stone", 2001],
  ['Alfonso Cuarón', "Harry Potter and the Prisoner of Azkaban", 2004],
  ['Mike Newell', 'Harry Potter and the Goblet of Fire', 2005],
  ['David Yates', 'Harry Potter and the Deathly Hallows: Part 2', 2011],
  ['Chris Columbus', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 2005],

  // --- Animation / Pixar / Ghibli ---
  ['Hayao Miyazaki', 'My Neighbor Totoro', 1988],
  ['Hayao Miyazaki', "Princess Mononoke", 1997],
  ['Hayao Miyazaki', "Howl's Moving Castle", 2004],
  ['Hayao Miyazaki', 'Kiki\'s Delivery Service', 1989],
  ['Hayao Miyazaki', 'The Wind Rises', 2013],
  ['Hayao Miyazaki', 'The Boy and the Heron', 2023],
  ['Isao Takahata', 'Grave of the Fireflies', 1988],
  ['Mamoru Hosoda', 'Your Name.', 2016],
  ['Makoto Shinkai', 'Weathering with You', 2019],
  ['Katsuhiro Otomo', 'Akira', 1988],
  ['Mamoru Oshii', 'Ghost in the Shell', 1995],
  ['Satoshi Kon', 'Perfect Blue', 1997],
  ['Satoshi Kon', 'Paprika', 2006],
  ['John Lasseter', "A Bug's Life", 1998],
  ['John Lasseter', 'Cars', 2006],
  ['John Lasseter', 'Toy Story 2', 1999],
  ['Pete Docter', 'Monsters, Inc.', 2001],
  ['Pete Docter', 'Inside Out', 2015],
  ['Pete Docter', 'Soul', 2020],
  ['Brad Bird', 'The Iron Giant', 1999],
  ['Brad Bird', 'The Incredibles', 2004],
  ['Brad Bird', 'Ratatouille', 2007],
  ['Andrew Stanton', 'Finding Nemo', 2003],
  ['Lee Unkrich', 'Coco', 2017],
  ['Domee Shi', 'Turning Red', 2022],
  ['Danny DeVito', 'Matilda', 1996],
  ['Roger Allers, Rob Minkoff', 'Aladdin', 1992],
  ['Ron Clements, John Musker', 'The Little Mermaid', 1989],
  ['Ron Clements, John Musker', 'Moana', 2016],
  ['Gary Trousdale, Kirk Wise', 'The Hunchback of Notre Dame', 1996],
  ['Chris Buck, Jennifer Lee', 'Frozen', 2013],
  ['Byron Howard, Rich Moore', 'Zootopia', 2016],
  ['Nick Park, Steve Box', 'Wallace & Gromit: The Curse of the Were-Rabbit', 2005],
  ['Nick Park', 'Chicken Run', 2000],
  ['Henry Selick', 'The Nightmare Before Christmas', 1993],
  ['Henry Selick', 'Coraline', 2009],
  ['Wes Anderson', 'Fantastic Mr. Fox', 2009],
  ['Wes Anderson', 'Isle of Dogs', 2018],
  ['Phil Lord, Christopher Miller', 'The Lego Movie', 2014],
  ['Bob Persichetti, Peter Ramsey, Rodney Rothman', 'Spider-Man: Into the Spider-Verse', 2018],
  ['Genndy Tartakovsky', 'Hotel Transylvania', 2012],
  ['Chris Sanders, Dean DeBlois', 'Lilo & Stitch', 2002],
  ['Dean DeBlois', 'How to Train Your Dragon', 2010],
  ['Eric Darnell, Tom McGrath', 'Madagascar', 2005],
  ['Carlos Saldanha', 'Rio', 2011],
  ['Tim Johnson', 'Antz', 1998],

  // --- Superhero / blockbuster franchises ---
  ['Jon Favreau', 'Iron Man', 2008],
  ['Joss Whedon', 'The Avengers', 2012],
  ['Anthony Russo, Joe Russo', 'Captain America: The Winter Soldier', 2014],
  ['Anthony Russo, Joe Russo', 'Avengers: Infinity War', 2018],
  ['Taika Waititi', 'Thor: Ragnarok', 2017],
  ['Ryan Coogler', 'Black Panther', 2018],
  ['James Gunn', 'Guardians of the Galaxy', 2014],
  ['James Gunn', 'Guardians of the Galaxy Vol. 2', 2017],
  ['Sam Raimi', 'Spider-Man', 2002],
  ['Sam Raimi', 'Spider-Man 2', 2004],
  ['Marc Webb', 'The Amazing Spider-Man', 2012],
  ['Jon Watts', 'Spider-Man: No Way Home', 2021],
  ['Bryan Singer', 'X2: X-Men United', 2003],
  ['Matthew Vaughn', 'X-Men: First Class', 2011],
  ['Zack Snyder', 'Man of Steel', 2013],
  ['Zack Snyder', 'Watchmen', 2009],
  ['Zack Snyder', '300', 2006],
  ['Richard Donner', 'Superman', 1978],
  ['Sam Mendes', 'Skyfall', 2012],
  ['Martin Campbell', 'Casino Royale', 2006],
  ['Terence Young', 'Dr. No', 1962],
  ['Guy Hamilton', 'Goldfinger', 1964],
  ['Brad Bird', 'Mission: Impossible – Ghost Protocol', 2011],
  ['Christopher McQuarrie', 'Mission: Impossible – Fallout', 2018],
  ['Justin Lin', 'Fast Five', 2011],
  ['James Wan', 'Furious 7', 2015],
  ['Denis Villeneuve', 'Sicario', 2015],
  ['Denis Villeneuve', 'Prisoners', 2013],
  ['Christopher Nolan', 'Interstellar', 2014],
  ['Christopher Nolan', 'Dunkirk', 2017],
  ['Christopher Nolan', 'Tenet', 2020],
  ['Christopher Nolan', 'Batman Begins', 2005],
  ['Christopher Nolan', 'The Dark Knight Rises', 2012],
  ['Christopher Nolan', 'The Prestige', 2006],
  ['Christopher Nolan', 'Insomnia', 2002],

  // --- Horror / thriller / sci-fi wave ---
  ['Ari Aster', 'Hereditary', 2018],
  ['Ari Aster', 'Midsommar', 2019],
  ['Robert Eggers', 'The Witch', 2015],
  ['Robert Eggers', 'The Lighthouse', 2019],
  ['Robert Eggers', 'Nosferatu', 2024],
  ['Jordan Peele', 'Us', 2019],
  ['Jordan Peele', 'Nope', 2022],
  ['James Wan', 'The Conjuring', 2013],
  ['James Wan', 'Saw', 2004],
  ['M. Night Shyamalan', 'Signs', 2002],
  ['M. Night Shyamalan', 'Unbreakable', 2000],
  ['David Fincher', 'Zodiac', 2007],
  ['David Fincher', 'Gone Girl', 2014],
  ['David Fincher', 'The Girl with the Dragon Tattoo', 2011],
  ['David Fincher', 'The Curious Case of Benjamin Button', 2008],
  ['Denis Villeneuve', 'Enemy', 2013],
  ['Alex Garland', 'Ex Machina', 2014],
  ['Alex Garland', 'Annihilation', 2018],
  ['Duncan Jones', 'Moon', 2009],
  ['Shane Carruth', 'Primer', 2004],
  ['Rian Johnson', 'Looper', 2012],
  ['Rian Johnson', 'Glass Onion', 2022],
  ['Bong Joon-ho', 'Memories of Murder', 2003],
  ['Bong Joon-ho', 'Snowpiercer', 2013],
  ['Park Chan-wook', 'Oldboy', 2003],
  ['Park Chan-wook', 'The Handmaiden', 2016],
  ['Kim Jee-woon', 'I Saw the Devil', 2010],
  ['Na Hong-jin', 'The Wailing', 2016],
  ['Hirokazu Kore-eda', 'Shoplifters', 2018],
  ['Yasujiro Ozu', 'Late Spring', 1949],
  ['Wong Kar-wai', 'In the Mood for Love', 2000],
  ['Wong Kar-wai', 'Chungking Express', 1994],
  ['Ang Lee', 'Life of Pi', 2012],
  ['Ang Lee', 'Brokeback Mountain', 2005],
  ['Alejandro G. Iñárritu', 'Birdman', 2014],
  ['Alejandro G. Iñárritu', 'The Revenant', 2015],
  ['Alejandro G. Iñárritu', 'Amores Perros', 2000],
  ['Alfonso Cuarón', 'Children of Men', 2006],
  ['Alfonso Cuarón', 'Gravity', 2013],
  ['Alfonso Cuarón', 'Roma', 2018],
  ['Alfonso Cuarón', 'Y Tu Mamá También', 2001],
  ['Guillermo del Toro', 'The Devil\'s Backbone', 2001],
  ['Guillermo del Toro', 'Pinocchio', 2022],
  ['Pedro Almodóvar', 'All About My Mother', 1999],
  ['Pedro Almodóvar', 'Talk to Her', 2002],
  ['Pedro Almodóvar', 'Volver', 2006],
  ['Michael Haneke', 'Amour', 2012],
  ['Michael Haneke', 'Funny Games', 1997],
  ['Lars von Trier', 'Melancholia', 2011],
  ['Lars von Trier', 'Dancer in the Dark', 2000],
  ['Yorgos Lanthimos', 'The Lobster', 2015],
  ['Yorgos Lanthimos', 'The Favourite', 2018],
  ['Céline Sciamma', 'Portrait of a Lady on Fire', 2019],
  ['Jacques Audiard', 'A Prophet', 2009],
  ['Matteo Garrone', 'Gomorrah', 2008],
  ['Paolo Sorrentino', 'The Great Beauty', 2013],
  ['Roberto Benigni', 'Life Is Beautiful', 1997],
  ['Giuseppe Tornatore', 'Cinema Paradiso', 1988],

  // --- 2000s-2020s American drama / comedy / indie ---
  ['Paul Thomas Anderson', 'Magnolia', 1999],
  ['Paul Thomas Anderson', 'Boogie Nights', 1997],
  ['Paul Thomas Anderson', 'Punch-Drunk Love', 2002],
  ['Paul Thomas Anderson', 'Phantom Thread', 2017],
  ['Paul Thomas Anderson', 'Licorice Pizza', 2021],
  ['Wes Anderson', 'Rushmore', 1998],
  ['Wes Anderson', 'The Royal Tenenbaums', 2001],
  ['Wes Anderson', 'Moonrise Kingdom', 2012],
  ['Wes Anderson', 'Asteroid City', 2023],
  ['Spike Jonze', 'Her', 2013],
  ['Spike Jonze', 'Adaptation.', 2002],
  ['Charlie Kaufman', 'Synecdoche, New York', 2008],
  ['Charlie Kaufman', "I'm Thinking of Ending Things", 2020],
  ['Noah Baumbach', 'Marriage Story', 2019],
  ['Noah Baumbach', 'The Squid and the Whale', 2005],
  ['Greta Gerwig', 'Little Women', 2019],
  ['Sofia Coppola', 'Lost in Translation', 2003],
  ['Sofia Coppola', 'The Virgin Suicides', 1999],
  ['Sofia Coppola', 'Marie Antoinette', 2006],
  ['Richard Linklater', 'Boyhood', 2014],
  ['Richard Linklater', 'Before Sunrise', 1995],
  ['Richard Linklater', 'Before Sunset', 2004],
  ['Richard Linklater', 'Dazed and Confused', 1993],
  ['Richard Linklater', 'School of Rock', 2003],
  ['Judd Apatow', 'The 40-Year-Old Virgin', 2005],
  ['Judd Apatow', 'Knocked Up', 2007],
  ['Adam McKay', 'The Big Short', 2015],
  ['Adam McKay', 'Anchorman: The Legend of Ron Burgundy', 2004],
  ['Adam McKay', "Don't Look Up", 2021],
  ['David O. Russell', 'Silver Linings Playbook', 2012],
  ['David O. Russell', 'American Hustle', 2013],
  ['David O. Russell', 'The Fighter', 2010],
  ['Tom Ford', 'A Single Man', 2009],
  ['Tom McCarthy', 'The Station Agent', 2003],
  ['Todd Field', 'Tár', 2022],
  ['Todd Field', 'In the Bedroom', 2001],
  ['Kelly Fremon Craig', 'The Edge of Seventeen', 2016],
  ['Olivia Wilde', 'Booksmart', 2019],
  ['Emerald Fennell', 'Promising Young Woman', 2020],
  ['Chloé Zhao', 'The Rider', 2017],
  ['Sean Baker', 'The Florida Project', 2017],
  ['Sean Baker', 'Anora', 2024],
  ['Debra Granik', "Winter's Bone", 2010],
  ['Kenneth Lonergan', 'Manchester by the Sea', 2016],
  ['Barry Jenkins', 'If Beale Street Could Talk', 2018],
  ['Taika Waititi', 'Jojo Rabbit', 2019],
  ['Taika Waititi', 'What We Do in the Shadows', 2014],
  ['Armando Iannucci', 'In the Loop', 2009],
  ['Edgar Wright', 'Shaun of the Dead', 2004],
  ['Edgar Wright', 'Hot Fuzz', 2007],
  ['Edgar Wright', 'Scott Pilgrim vs. the World', 2010],
  ['Edgar Wright', 'Baby Driver', 2017],
  ['Guy Ritchie', 'Lock, Stock and Two Smoking Barrels', 1998],
  ['Guy Ritchie', 'Snatch', 2000],
  ['Danny Boyle', '28 Days Later', 2002],
  ['Danny Boyle', 'Sunshine', 2007],
  ['Steve McQueen', '12 Years a Slave', 2013],
  ['Steve McQueen', 'Shame', 2011],
  ['Ryan Coogler', 'Fruitvale Station', 2013],
  ['Ryan Coogler', 'Creed', 2015],
  ['Spike Lee', 'BlacKkKlansman', 2018],
  ['Spike Lee', 'Malcolm X', 1992],
  ['John Singleton', 'Boyz n the Hood', 1991],
  ['Antoine Fuqua', 'Training Day', 2001],
  ['Denzel Washington', 'Fences', 2016],
  ['Damien Chazelle', 'Babylon', 2022],
  ['Damien Chazelle', 'First Man', 2018],
  ['Florian Zeller', 'The Father', 2020],
  ['Kenneth Branagh', 'Belfast', 2021],
  ['Jane Campion', 'The Power of the Dog', 2021],
  ['Jane Campion', 'The Piano', 1993],
  ['Martin McDonagh', 'In Bruges', 2008],
  ['Martin McDonagh', 'Three Billboards Outside Ebbing, Missouri', 2017],
  ['Kogonada', 'After Yang', 2021],
  ['Celine Song', 'Past Lives', 2023],
  ['Justine Triet', 'Anatomy of a Fall', 2023],
  ['Jonathan Glazer', 'The Zone of Interest', 2023],
  ['Jonathan Glazer', 'Under the Skin', 2013],
  ['Luca Guadagnino', 'Call Me by Your Name', 2017],
];

module.exports = buildOptions(RAW_MOVIES);
