const { buildOptions } = require('./build-options');

// Curated list of widely-recognized video games spanning eras, genres and platforms, used
// as the fixed option set for the "Best Video Game of All Time" poll.
// Tuples are [developer, title, year].
const RAW_GAMES = [
  ['Taito', 'Space Invaders', 1978],
  ['Namco', 'Pac-Man', 1980],
  ['Nintendo', 'Donkey Kong', 1981],
  ['Alexey Pajitnov', 'Tetris', 1984],
  ['Nintendo', 'Super Mario Bros.', 1985],
  ['Nintendo', 'The Legend of Zelda', 1986],
  ['Capcom', 'Mega Man 2', 1988],
  ['Nintendo', 'Super Mario Bros. 3', 1988],
  ['Capcom', 'Street Fighter II', 1991],
  ['Nintendo', 'Super Mario World', 1990],
  ['Nintendo', 'The Legend of Zelda: A Link to the Past', 1991],
  ['Square', 'Final Fantasy VI', 1994],
  ['Nintendo', 'Super Metroid', 1994],
  ['Square', 'Chrono Trigger', 1995],
  ['Rare', 'Donkey Kong Country', 1994],
  ['Game Freak', 'Pokémon Red and Blue', 1996],
  ['Nintendo', 'Super Mario 64', 1996],
  ['Nintendo', 'The Legend of Zelda: Ocarina of Time', 1998],
  ['Rare', 'GoldenEye 007', 1997],
  ['Square', 'Final Fantasy VII', 1997],
  ['Konami', 'Metal Gear Solid', 1998],
  ['Capcom', 'Resident Evil 2', 1998],
  ['Konami', 'Castlevania: Symphony of the Night', 1997],
  ['Naughty Dog', 'Crash Bandicoot', 1996],
  ['Insomniac Games', 'Spyro the Dragon', 1998],
  ['Valve', 'Half-Life', 1998],
  ['Blizzard Entertainment', 'StarCraft', 1998],
  ['Blizzard Entertainment', 'Diablo II', 2000],
  ['Rare', 'Banjo-Kazooie', 1998],
  ['Game Freak', 'Pokémon Gold and Silver', 1999],
  ['Nintendo', 'The Legend of Zelda: Majora’s Mask', 2000],
  ['Neversoft', 'Tony Hawk’s Pro Skater 2', 2000],
  ['Rockstar North', 'Grand Theft Auto III', 2001],
  ['Rockstar North', 'Grand Theft Auto: Vice City', 2002],
  ['Rockstar North', 'Grand Theft Auto: San Andreas', 2004],
  ['Konami', 'Metal Gear Solid 3: Snake Eater', 2004],
  ['Team Ico', 'ICO', 2001],
  ['Team Ico', 'Shadow of the Colossus', 2005],
  ['Square', 'Final Fantasy X', 2001],
  ['Square Enix', 'Kingdom Hearts', 2002],
  ['Capcom', 'Resident Evil 4', 2005],
  ['Bungie', 'Halo: Combat Evolved', 2001],
  ['Bungie', 'Halo 2', 2004],
  ['Nintendo', 'The Legend of Zelda: The Wind Waker', 2002],
  ['HAL Laboratory', 'Super Smash Bros. Melee', 2001],
  ['Retro Studios', 'Metroid Prime', 2002],
  ['Nintendo', 'Animal Crossing', 2001],
  ['Blizzard Entertainment', 'World of Warcraft', 2004],
  ['Valve', 'Half-Life 2', 2004],
  ['SCE Santa Monica Studio', 'God of War', 2005],
  ['SCE Santa Monica Studio', 'God of War II', 2007],
  ['Harmonix', 'Guitar Hero', 2005],
  ['Namco', 'Katamari Damacy', 2004],
  ['Valve', 'Portal', 2007],
  ['2K Boston', 'BioShock', 2007],
  ['Infinity Ward', 'Call of Duty 4: Modern Warfare', 2007],
  ['Infinity Ward', 'Call of Duty: Modern Warfare 2', 2009],
  ['BioWare', 'Mass Effect', 2007],
  ['BioWare', 'Mass Effect 2', 2010],
  ['Bethesda Game Studios', 'The Elder Scrolls IV: Oblivion', 2006],
  ['Bethesda Game Studios', 'The Elder Scrolls V: Skyrim', 2011],
  ['Bethesda Game Studios', 'Fallout 3', 2008],
  ['Obsidian Entertainment', 'Fallout: New Vegas', 2010],
  ['Rockstar Games', 'Red Dead Redemption', 2010],
  ['Rockstar North', 'Grand Theft Auto IV', 2008],
  ['Rockstar North', 'Grand Theft Auto V', 2013],
  ['Naughty Dog', 'Uncharted 2: Among Thieves', 2009],
  ['Naughty Dog', 'The Last of Us', 2013],
  ['Rocksteady Studios', 'Batman: Arkham Asylum', 2009],
  ['Rocksteady Studios', 'Batman: Arkham City', 2011],
  ['Nintendo', 'Super Mario Galaxy', 2007],
  ['Nintendo', 'Super Mario Galaxy 2', 2010],
  ['Nintendo', 'The Legend of Zelda: Twilight Princess', 2006],
  ['Nintendo', 'The Legend of Zelda: Skyward Sword', 2011],
  ['Number None', 'Braid', 2008],
  ['Playdead', 'Limbo', 2010],
  ['Mojang', 'Minecraft', 2011],
  ['FromSoftware', 'Demon’s Souls', 2009],
  ['FromSoftware', 'Dark Souls', 2011],
  ['Thatgamecompany', 'Journey', 2012],
  ['Valve', 'Left 4 Dead 2', 2009],
  ['Irrational Games', 'BioShock Infinite', 2013],
  ['Visceral Games', 'Dead Space', 2008],
  ['Ubisoft Montreal', 'Assassin’s Creed II', 2009],
  ['Nintendo', 'Super Smash Bros. Brawl', 2008],
  ['Nintendo', 'Wii Sports', 2006],
  ['CD Projekt Red', 'The Witcher 3: Wild Hunt', 2015],
  ['FromSoftware', 'Dark Souls III', 2016],
  ['FromSoftware', 'Bloodborne', 2015],
  ['Toby Fox', 'Undertale', 2015],
  ['Blizzard Entertainment', 'Overwatch', 2016],
  ['ConcernedApe', 'Stardew Valley', 2016],
  ['id Software', 'DOOM', 2016],
  ['Team Cherry', 'Hollow Knight', 2017],
  ['Nintendo', 'The Legend of Zelda: Breath of the Wild', 2017],
  ['Nintendo', 'Super Mario Odyssey', 2017],
  ['Atlus', 'Persona 5', 2017],
  ['Matt Makes Games', 'Celeste', 2018],
  ['Rockstar Games', 'Red Dead Redemption 2', 2018],
  ['Santa Monica Studio', 'God of War', 2018],
  ['Insomniac Games', 'Marvel’s Spider-Man', 2018],
  ['FromSoftware', 'Sekiro: Shadows Die Twice', 2019],
  ['Mobius Digital', 'Outer Wilds', 2019],
  ['ZA/UM', 'Disco Elysium', 2019],
  ['Epic Games', 'Fortnite', 2017],
  ['Respawn Entertainment', 'Apex Legends', 2019],
  ['Studio MDHR', 'Cuphead', 2017],
  ['Nintendo', 'Animal Crossing: New Horizons', 2020],
  ['Supergiant Games', 'Hades', 2020],
  ['Naughty Dog', 'The Last of Us Part II', 2020],
  ['Sucker Punch Productions', 'Ghost of Tsushima', 2020],
  ['Square Enix', 'Final Fantasy VII Remake', 2020],
  ['Hazelight Studios', 'It Takes Two', 2021],
  ['FromSoftware', 'Elden Ring', 2022],
  ['Santa Monica Studio', 'God of War Ragnarök', 2022],
  ['Guerrilla Games', 'Horizon Forbidden West', 2022],
  ['Larian Studios', 'Baldur’s Gate 3', 2023],
  ['Nintendo', 'The Legend of Zelda: Tears of the Kingdom', 2023],
  ['Insomniac Games', 'Marvel’s Spider-Man 2', 2023],
  ['Remedy Entertainment', 'Alan Wake II', 2023],
  ['Nintendo', 'Super Mario Bros. Wonder', 2023],
  ['Arrowhead Game Studios', 'Helldivers 2', 2024],
  ['Square Enix', 'Final Fantasy VII Rebirth', 2024],

  // --- Arcade & early consoles ---
  ['Atari', 'Pong', 1972],
  ['Atari', 'Asteroids', 1979],
  ['Atari', 'Missile Command', 1980],
  ['Williams Electronics', 'Defender', 1981],
  ['Nintendo', 'Donkey Kong Jr.', 1982],
  ['Midway', 'Ms. Pac-Man', 1982],
  ['Konami', 'Frogger', 1981],
  ['Bally Midway', 'Tron', 1982],
  ['Sega', 'OutRun', 1986],
  ['Sega', 'Altered Beast', 1988],
  ['Capcom', 'Ghosts \'n Goblins', 1985],
  ['Capcom', "1942", 1984],
  ['Data East', 'BurgerTime', 1982],
  ['Nintendo', 'Ice Climber', 1985],
  ['Nintendo', 'Kid Icarus', 1986],
  ['Nintendo', 'Metroid', 1986],
  ['Nintendo', 'Duck Hunt', 1984],
  ['Nintendo', 'Excitebike', 1984],
  ['Nintendo', 'R.C. Pro-Am', 1987],
  ['Konami', 'Contra', 1987],
  ['Konami', 'Gradius', 1985],
  ['Capcom', 'Bionic Commando', 1988],
  ['Taito', 'Bubble Bobble', 1986],
  ['Technos Japan', 'Double Dragon', 1987],

  // --- SNES / Genesis era ---
  ['Sega', 'Sonic the Hedgehog', 1991],
  ['Sega', 'Sonic the Hedgehog 2', 1992],
  ['Sega', 'Sonic 3 & Knuckles', 1994],
  ['Sega', 'Streets of Rage 2', 1992],
  ['Treasure', 'Gunstar Heroes', 1993],
  ['Squaresoft', 'Super Mario RPG', 1996],
  ['Nintendo', "Kirby's Adventure", 1993],
  ['HAL Laboratory', 'Kirby Super Star', 1996],
  ['Nintendo', 'Star Fox', 1993],
  ['Nintendo', 'Star Fox 64', 1997],
  ['Rare', 'Killer Instinct', 1994],
  ['Capcom', 'Mega Man X', 1993],
  ['Capcom', 'Mega Man X4', 1997],
  ['Konami', 'Castlevania: Rondo of Blood', 1993],
  ['Squaresoft', 'Secret of Mana', 1993],
  ['Squaresoft', 'Final Fantasy IV', 1991],
  ['Squaresoft', 'Live A Live', 1994],
  ['Enix', 'Dragon Quest V', 1992],
  ['Nintendo', 'EarthBound', 1994],
  ['Nintendo', 'Yoshi\'s Island', 1995],
  ['DMA Design', 'Lemmings', 1991],
  ['Bullfrog Productions', 'Populous', 1989],
  ['Bullfrog Productions', 'Theme Park', 1994],
  ['Maxis', 'SimCity 2000', 1993],
  ['Maxis', 'SimCity', 1989],
  ['id Software', 'Wolfenstein 3D', 1992],
  ['id Software', 'DOOM', 1993],
  ['id Software', 'DOOM II', 1994],
  ['id Software', 'Quake', 1996],
  ['id Software', 'Quake II', 1997],
  ['LucasArts', 'The Secret of Monkey Island', 1990],
  ['LucasArts', 'Day of the Tentacle', 1993],
  ['LucasArts', 'Grim Fandango', 1998],
  ['LucasArts', 'Sam & Max Hit the Road', 1993],
  ['LucasArts', 'Star Wars: TIE Fighter', 1994],
  ['Cyan', 'Myst', 1993],
  ['Trilobyte', 'The 7th Guest', 1993],
  ['Revolution Software', 'Broken Sword', 1996],
  ['Blizzard Entertainment', 'Warcraft II: Tides of Darkness', 1995],
  ['Blizzard Entertainment', 'Diablo', 1996],
  ['Westwood Studios', 'Command & Conquer', 1995],
  ['Westwood Studios', 'Command & Conquer: Red Alert', 1996],
  ['Ensemble Studios', 'Age of Empires II', 1999],
  ['Firaxis Games', 'Sid Meier\'s Civilization II', 1996],
  ['MicroProse', 'Sid Meier\'s Civilization', 1991],
  ['Bethesda Softworks', 'The Elder Scrolls II: Daggerfall', 1996],
  ['Bethesda Softworks', 'The Elder Scrolls III: Morrowind', 2002],
  ['Bungie', 'Marathon', 1994],
  ['Bungie', 'Myth: The Fallen Lords', 1997],
  ['Looking Glass Studios', 'Thief: The Dark Project', 1998],
  ['Looking Glass Studios', 'System Shock 2', 1999],
  ['Ion Storm', 'Deus Ex', 2000],
  ['Valve', 'Team Fortress Classic', 1996],
  ['Remedy Entertainment', 'Max Payne', 2001],
  ['Remedy Entertainment', 'Max Payne 2: The Fall of Max Payne', 2003],
  ['Epic MegaGames', 'Unreal Tournament', 1999],
  ['Epic MegaGames', 'Unreal', 1998],
  ['Rare', 'Donkey Kong Country 2: Diddy\'s Kong Quest', 1995],
  ['Rare', 'Jet Force Gemini', 1999],
  ['Rare', 'Perfect Dark', 2000],
  ['Nintendo', 'Pokémon Stadium', 2000],
  ['Game Freak', 'Pokémon Crystal', 2000],
  ['Game Freak', 'Pokémon Ruby and Sapphire', 2002],
  ['Game Freak', 'Pokémon Emerald', 2004],
  ['Game Freak', 'Pokémon Diamond and Pearl', 2006],
  ['Camelot Software Planning', 'Golden Sun', 2001],
  ['Konami', 'Suikoden II', 1998],
  ['Squaresoft', 'Vagrant Story', 2000],
  ['Squaresoft', 'Xenogears', 1998],
  ['Squaresoft', 'Chrono Cross', 1999],
  ['Squaresoft', 'Final Fantasy VIII', 1999],
  ['Squaresoft', 'Final Fantasy IX', 2000],
  ['Square Enix', 'Final Fantasy X-2', 2003],
  ['Square Enix', 'Final Fantasy XII', 2006],
  ['Square Enix', 'Kingdom Hearts II', 2005],

  // --- PS2 / GameCube / Xbox era ---
  ['Sega', 'Jet Set Radio', 2000],
  ['Sega', 'Rez', 2001],
  ['Sega', 'Super Monkey Ball', 2001],
  ['Sega', 'Shenmue', 1999],
  ['Sega', 'Shenmue II', 2001],
  ['Sega', 'Virtua Fighter 4', 2001],
  ['Sega', 'Crazy Taxi', 1999],
  ['Sega', 'Skies of Arcadia', 2000],
  ['Sega', 'Phantasy Star Online', 2000],
  ['Sega', "Sonic Adventure", 1998],
  ['Sonic Team', 'Sonic Adventure 2', 2001],
  ['Clover Studio', 'Ōkami', 2006],
  ['Clover Studio', 'Viewtiful Joe', 2003],
  ['Grasshopper Manufacture', 'Killer7', 2005],
  ['Grasshopper Manufacture', 'No More Heroes', 2007],
  ['PlatinumGames', 'Bayonetta', 2009],
  ['PlatinumGames', 'Bayonetta 2', 2014],
  ['PlatinumGames', 'Vanquish', 2010],
  ['PlatinumGames', 'Metal Gear Rising: Revengeance', 2013],
  ['Capcom', 'Devil May Cry', 2001],
  ['Capcom', 'Devil May Cry 3: Dante\'s Awakening', 2005],
  ['Capcom', 'Devil May Cry 5', 2019],
  ['Capcom', 'Monster Hunter', 2004],
  ['Capcom', 'Monster Hunter World', 2018],
  ['Capcom', 'Monster Hunter Rise', 2021],
  ['Capcom', 'Street Fighter III: 3rd Strike', 1999],
  ['Capcom', 'Marvel vs. Capcom 2', 2000],
  ['Capcom', 'Ace Attorney: Phoenix Wright', 2001],
  ['Capcom', 'Dead Rising', 2006],
  ['Capcom', 'Resident Evil', 1996],
  ['Capcom', 'Resident Evil 3: Nemesis', 1999],
  ['Capcom', 'Resident Evil Village', 2021],
  ['Konami', 'Metal Gear Solid 2: Sons of Liberty', 2001],
  ['Konami', 'Metal Gear Solid 4: Guns of the Patriots', 2008],
  ['Konami', 'Silent Hill', 1999],
  ['Konami', 'Silent Hill 2', 2001],
  ['Konami', 'Dance Dance Revolution', 1998],
  ['Harmonix', 'Rock Band', 2007],
  ['Namco', 'Tekken 3', 1998],
  ['Namco', 'Tekken Tag Tournament', 1999],
  ['Namco', 'Soulcalibur', 1998],
  ['Namco', 'Ridge Racer Type 4', 1999],
  ['Namco Bandai', 'Tales of Symphonia', 2003],
  ['Midway Games', 'Mortal Kombat', 1992],
  ['NetherRealm Studios', 'Mortal Kombat 9', 2011],
  ['NetherRealm Studios', 'Mortal Kombat 11', 2019],
  ['NetherRealm Studios', 'Injustice 2', 2017],
  ['Arc System Works', 'Guilty Gear Xrd', 2014],
  ['Arc System Works', 'Guilty Gear Strive', 2021],
  ['French Bread', 'Under Night In-Birth', 2012],
  ['Team Ninja', 'Ninja Gaiden', 2004],
  ['Team Ninja', 'Dead or Alive 2', 1999],
  ['Rockstar Games', 'Bully', 2006],
  ['Rockstar Games', 'Max Payne 3', 2012],
  ['Rockstar Games', 'L.A. Noire', 2011],
  ['Rockstar North', 'Manhunt', 2003],
  ['Insomniac Games', 'Ratchet & Clank', 2002],
  ['Insomniac Games', 'Ratchet & Clank: A Crack in Time', 2009],
  ['Insomniac Games', 'Ratchet & Clank: Rift Apart', 2021],
  ['Naughty Dog', 'Jak and Daxter: The Precursor Legacy', 2001],
  ['Sucker Punch Productions', 'Sly Cooper and the Thievius Raccoonus', 2002],
  ['Sucker Punch Productions', 'Infamous', 2009],
  ['Sucker Punch Productions', 'Infamous Second Son', 2014],
  ['Ubisoft Montpellier', 'Beyond Good & Evil', 2003],
  ['Ubisoft Montreal', 'Prince of Persia: The Sands of Time', 2003],
  ['Ubisoft Montreal', 'Assassin\'s Creed', 2007],
  ['Ubisoft Montreal', 'Assassin\'s Creed II', 2009],
  ['Ubisoft Montreal', 'Assassin\'s Creed: Brotherhood', 2010],
  ['Ubisoft Montreal', 'Assassin\'s Creed IV: Black Flag', 2013],
  ['Ubisoft Quebec', 'Assassin\'s Creed Odyssey', 2018],
  ['Ubisoft Montreal', 'Far Cry 3', 2012],
  ['Ubisoft Montreal', 'Far Cry 4', 2014],
  ['Ubisoft Montreal', 'Watch Dogs', 2014],
  ['Ubisoft Milan', 'Rayman Origins', 2011],
  ['Ubisoft Montpellier', 'Rayman Legends', 2013],
  ['Avalanche Studios', 'Just Cause 2', 2010],
  ['United Front Games', 'Sleeping Dogs', 2012],
  ['Rockstar Toronto', 'Mafia II', 2010],
  ['2K Czech', 'Mafia: The City of Lost Heaven', 2002],
  ['Crystal Dynamics', 'Tomb Raider', 2013],
  ['Core Design', 'Tomb Raider II', 1997],
  ['Eidos Interactive', 'Tomb Raider', 1996],
  ['Crystal Dynamics', 'Rise of the Tomb Raider', 2015],

  // --- Modern PC / cross-platform ---
  ['Facepunch Studios', "Garry's Mod", 2006],
  ['Media Molecule', 'LittleBigPlanet', 2008],
  ['Media Molecule', 'Dreams', 2020],
  ['thatgamecompany', 'Flower', 2009],
  ['thatgamecompany', 'Abzû', 2016],
  ['Giant Sparrow', 'What Remains of Edith Finch', 2017],
  ['Giant Sparrow', 'The Unfinished Swan', 2012],
  ['Campo Santo', 'Firewatch', 2016],
  ['Fullbright', 'Gone Home', 2013],
  ['Playdead', 'Inside', 2016],
  ['Tarsier Studios', 'Little Nightmares', 2017],
  ['Frictional Games', 'Amnesia: The Dark Descent', 2010],
  ['Frictional Games', 'SOMA', 2015],
  ['Creative Assembly', 'Alien: Isolation', 2014],
  ['Red Barrels', 'Outlast', 2013],
  ['Behaviour Interactive', 'Dead by Daylight', 2016],
  ['Kinetic Games', 'Phasmophobia', 2020],
  ['Scott Cawthon', 'Five Nights at Freddy\'s', 2014],
  ['Toby Fox', 'Deltarune', 2018],
  ['Team Cherry', 'Hollow Knight: Silksong', 2025],
  ['Motion Twin', 'Dead Cells', 2018],
  ['Derek Yu', 'Spelunky', 2008],
  ['Mossmouth', 'Spelunky 2', 2020],
  ['Dennaton Games', 'Hotline Miami', 2012],
  ['Devolver Digital', 'Katana ZERO', 2019],
  ['Ninja Theory', 'Hellblade: Senua\'s Sacrifice', 2017],
  ['Klei Entertainment', 'Don\'t Starve', 2013],
  ['Klei Entertainment', 'Oxygen Not Included', 2019],
  ['Coffee Stain Studios', 'Deep Rock Galactic', 2020],
  ['Facepunch Studios', 'Rust', 2018],
  ['Innersloth', 'Among Us', 2018],
  ['Mediatonic', 'Fall Guys', 2020],
  ['Bossa Studios', 'Surgeon Simulator', 2013],
  ['Curve Digital', 'Human: Fall Flat', 2016],
  ['Hazelight Studios', 'A Way Out', 2018],
  ['Ghost Town Games', 'Overcooked', 2016],
  ['Re-Logic', 'Terraria', 2011],
  ['Ludeon Studios', 'RimWorld', 2018],
  ['Wube Software', 'Factorio', 2020],
  ['Introversion Software', 'Prison Architect', 2015],
  ['Two Point Studios', 'Two Point Hospital', 2018],
  ['Bullfrog Productions', 'Theme Hospital', 1997],
  ['Maxis', 'The Sims', 2000],
  ['Maxis', 'The Sims 4', 2014],
  ['Colossal Order', 'Cities: Skylines', 2015],
  ['Squad', 'Kerbal Space Program', 2015],
  ['Frontier Developments', 'Planet Coaster', 2016],
  ['Chucklefish', 'Starbound', 2016],
  ['Chucklefish', 'Wargroove', 2019],
  ['Klei Entertainment', 'Invisible, Inc.', 2015],
  ['Firaxis Games', 'XCOM: Enemy Unknown', 2012],
  ['Firaxis Games', 'XCOM 2', 2016],
  ['Subset Games', 'Into the Breach', 2018],
  ['Subset Games', 'FTL: Faster Than Light', 2012],
  ['Mega Crit', 'Slay the Spire', 2019],
  ['LocalThunk', 'Balatro', 2024],
  ['Hopoo Games', 'Risk of Rain 2', 2020],
  ['Dodge Roll', 'Enter the Gungeon', 2016],
  ['poncle', 'Vampire Survivors', 2022],
  ['Bethesda Game Studios', 'Fallout 4', 2015],
  ['Bethesda Game Studios', 'Fallout 76', 2018],
  ['Bethesda Game Studios', 'Starfield', 2023],
  ['Larian Studios', 'Divinity: Original Sin II', 2017],
  ['Obsidian Entertainment', 'Pillars of Eternity', 2015],
  ['Obsidian Entertainment', 'The Outer Worlds', 2019],
  ['inXile Entertainment', 'Wasteland 2', 2014],
  ['BioWare', 'Star Wars: Knights of the Old Republic', 2003],
  ['BioWare', 'Dragon Age: Origins', 2009],
  ['BioWare', 'Baldur\'s Gate II: Shadows of Amn', 2000],
  ['Black Isle Studios', 'Planescape: Torment', 1999],
  ['Black Isle Studios', 'Fallout', 1997],
  ['Black Isle Studios', 'Fallout 2', 1998],
  ['CD Projekt Red', 'The Witcher 2: Assassins of Kings', 2011],
  ['CD Projekt Red', 'Cyberpunk 2077', 2020],
  ['Arkane Studios', 'Dishonored', 2012],
  ['Arkane Studios', 'Dishonored 2', 2016],
  ['Arkane Studios', 'Prey', 2017],
  ['IO Interactive', 'Hitman: Blood Money', 2006],
  ['IO Interactive', 'Hitman', 2016],
  ['Eidos Montréal', 'Deus Ex: Human Revolution', 2011],
  ['Remedy Entertainment', 'Alan Wake', 2010],
  ['Remedy Entertainment', 'Control', 2019],
  ['Remedy Entertainment', 'Quantum Break', 2016],
  ['Kojima Productions', 'Death Stranding', 2019],
  ['Guerrilla Games', 'Horizon Zero Dawn', 2017],
  ['Sony Bend', 'Days Gone', 2019],
  ['Ryu Ga Gotoku Studio', 'Yakuza 0', 2015],
  ['Ryu Ga Gotoku Studio', 'Like a Dragon: Yakuza 7', 2020],
  ['Ryu Ga Gotoku Studio', 'Judgment', 2018],
  ['Atlus', 'Persona 3', 2006],
  ['Atlus', 'Persona 4 Golden', 2008],
  ['Atlus', 'Persona 5 Royal', 2019],
  ['Atlus', 'Shin Megami Tensei III: Nocturne', 2003],
  ['Atlus', 'Catherine', 2011],
  ['Nippon Ichi Software', 'Disgaea: Hour of Darkness', 2003],
  ['Square Enix', 'Tactics Ogre: Let Us Cling Together', 1995],
  ['Square Enix', 'Final Fantasy Tactics', 1997],
  ['Square Enix', 'Nier: Automata', 2017],
  ['Cavia', 'Nier', 2010],
  ['Square Enix', 'Dragon Quest XI', 2017],
  ['Square Enix', 'Octopath Traveler', 2018],
  ['Monolith Soft', 'Xenoblade Chronicles', 2010],
  ['Monolith Soft', 'Xenoblade Chronicles 3', 2022],
  ['Intelligent Systems', 'Fire Emblem: Awakening', 2012],
  ['Intelligent Systems', 'Fire Emblem: Three Houses', 2019],
  ['Intelligent Systems', 'Advance Wars', 2001],
  ['Nintendo', 'Paper Mario: The Thousand-Year Door', 2004],
  ['Nintendo', 'Super Mario Sunshine', 2002],
  ['Nintendo', 'Super Paper Mario', 2007],
  ['Nintendo', 'New Super Mario Bros. Wii', 2009],
  ['Nintendo', 'Mario Kart 64', 1996],
  ['Nintendo', 'Mario Kart: Double Dash!!', 2003],
  ['Nintendo', 'Mario Kart 8 Deluxe', 2017],
  ['Nintendo', 'Mario Party', 1998],
  ['HAL Laboratory', 'Super Smash Bros.', 1999],
  ['Nintendo', 'Super Smash Bros. Ultimate', 2018],
  ['Nintendo', 'Splatoon', 2015],
  ['Nintendo', 'Splatoon 2', 2017],
  ['Nintendo', 'Splatoon 3', 2022],
  ['Nintendo', 'Pikmin', 2001],
  ['Nintendo', 'Pikmin 3', 2013],
  ['Nintendo', 'Luigi\'s Mansion', 2001],
  ['Nintendo', 'Metroid Prime 2: Echoes', 2004],
  ['Nintendo', 'Metroid Fusion', 2002],
  ['Nintendo', 'Metroid Dread', 2021],
  ['Nintendo', 'Metroid Prime Remastered', 2023],
  ['Nintendo', 'Xenoblade Chronicles 2', 2017],
  ['Nintendo', 'Pokémon Legends: Arceus', 2022],
  ['Nintendo', 'Pokémon Scarlet and Violet', 2022],
  ['Game Freak', 'Pokémon X and Y', 2013],
  ['Game Freak', 'Pokémon Sword and Shield', 2019],
  ['HAL Laboratory', "Kirby and the Forgotten Land", 2022],
  ['Retro Studios', 'Donkey Kong Country Returns', 2010],
  ['Nintendo EPD', 'Animal Crossing: Wild World', 2005],
  ['Nintendo', 'Nintendogs', 2005],
  ['Nintendo', 'Wii Sports Resort', 2009],
  ['Nintendo', 'Wii Fit', 2007],
  ['Nintendo', 'Wii Play', 2006],
  ['Nintendo SPD', 'Brain Age', 2005],
  ['Nintendo', 'Tetris (Game Boy)', 1989],
  ['Alexey Pajitnov', 'Tetris Effect', 2018],
  ['Sega', 'Puyo Puyo Tetris', 2014],
  ['Q Entertainment', 'Lumines', 2004],
  ['PopCap Games', 'Bejeweled', 2001],
  ['PopCap Games', 'Peggle', 2007],
  ['PopCap Games', 'Plants vs. Zombies', 2009],
  ['Halfbrick Studios', 'Fruit Ninja', 2010],
  ['Rovio Entertainment', 'Angry Birds', 2009],
  ['dotGears', 'Flappy Bird', 2013],
  ['Imangi Studios', 'Temple Run', 2011],
  ['King', 'Candy Crush Saga', 2012],
  ['Supercell', 'Clash of Clans', 2012],
  ['Supercell', 'Clash Royale', 2016],
  ['Supercell', 'Brawl Stars', 2018],
  ['Niantic', 'Pokémon GO', 2016],
  ['miHoYo', 'Genshin Impact', 2020],
  ['HoYoverse', 'Honkai: Star Rail', 2023],
  ['Riot Games', 'League of Legends', 2009],
  ['Riot Games', 'Valorant', 2020],
  ['Valve', 'Dota 2', 2013],
  ['Valve', 'Counter-Strike', 2000],
  ['Valve', 'Counter-Strike: Global Offensive', 2012],
  ['Valve', 'Team Fortress 2', 2007],
  ['Valve', 'Artifact', 2018],
  ['Mojang', 'Minecraft: Dungeons', 2020],
  ['PUBG Studios', 'PUBG: Battlegrounds', 2017],
  ['Digital Extremes', 'Warframe', 2013],
  ['Bungie', 'Destiny', 2014],
  ['Bungie', 'Destiny 2', 2017],
  ['Bungie', 'Halo 3', 2007],
  ['343 Industries', 'Halo 4', 2012],
  ['343 Industries', 'Halo Infinite', 2021],
  ['Turtle Rock Studios', 'Left 4 Dead', 2008],
  ['Starbreeze Studios', 'Payday 2', 2013],
  ['Respawn Entertainment', 'Titanfall 2', 2016],
  ['DICE', 'Battlefield 1', 2016],
  ['DICE', 'Battlefield 3', 2011],
  ['Infinity Ward', 'Call of Duty: Black Ops', 2010],
  ['Treyarch', 'Call of Duty: Black Ops II', 2012],
  ['Ubisoft Montreal', 'Rainbow Six Siege', 2015],
  ['Psyonix', 'Rocket League', 2015],
  ['EA Sports', 'FIFA 14', 2013],
  ['EA Sports', 'EA Sports FC 24', 2023],
  ['EA Tiburon', 'Madden NFL 2004', 2003],
  ['Visual Concepts', 'NBA 2K21', 2020],
  ['Sports Interactive', 'Football Manager 2021', 2020],
  ['Polyphony Digital', 'Gran Turismo 3: A-Spec', 2001],
  ['Polyphony Digital', 'Gran Turismo 4', 2004],
  ['Polyphony Digital', 'Gran Turismo 7', 2022],
  ['Turn 10 Studios', 'Forza Motorsport 4', 2011],
  ['Playground Games', 'Forza Horizon 4', 2018],
  ['Playground Games', 'Forza Horizon 5', 2021],
  ['Criterion Games', 'Burnout 3: Takedown', 2004],
  ['EA Black Box', 'Need for Speed: Most Wanted', 2005],
  ['Nintendo', 'F-Zero GX', 2003],
  ['Codemasters', 'F1 2021', 2021],
  ['Milestone', 'Ride 4', 2020],
  ['NaturalMotion', 'CSR Racing', 2012],
  ['Introversion Software', 'DEFCON', 2006],
  ['Amplitude Studios', 'Endless Space', 2012],
  ['Sid Meier', 'Sid Meier\'s Alpha Centauri', 1999],
  ['Firaxis Games', 'Sid Meier\'s Civilization V', 2010],
  ['Firaxis Games', 'Sid Meier\'s Civilization VI', 2016],
  ['Creative Assembly', 'Total War: Warhammer II', 2017],
  ['Creative Assembly', 'Rome: Total War', 2004],
  ['Blizzard Entertainment', 'Warcraft III: Reign of Chaos', 2002],
  ['Blizzard Entertainment', 'StarCraft II: Wings of Liberty', 2010],
  ['Blizzard Entertainment', 'Diablo III', 2012],
  ['Blizzard Entertainment', 'Diablo IV', 2023],
  ['Blizzard Entertainment', 'Hearthstone', 2014],
  ['Blizzard Entertainment', 'Overwatch 2', 2022],
  ['Grinding Gear Games', 'Path of Exile', 2013],
  ['Runic Games', 'Torchlight II', 2012],
  ['Jagex', 'RuneScape', 2001],
  ['Jagex', 'Old School RuneScape', 2013],
  ['CCP Games', 'EVE Online', 2003],
  ['ArenaNet', 'Guild Wars 2', 2012],
  ['Square Enix', 'Final Fantasy XIV: A Realm Reborn', 2013],
  ['FromSoftware', 'Armored Core VI: Fires of Rubicon', 2023],
  ['FromSoftware', 'Sekiro', 2019],
  ['Amy Hennig', 'Uncharted: Drake\'s Fortune', 2007],
  ['Naughty Dog', 'Uncharted 4: A Thief\'s End', 2016],
  ['Sony Interactive Entertainment', 'The Last Guardian', 2016],
  ['Sony Santa Monica', 'God of War: Ascension', 2013],
  ['SIE Bend Studio', 'Syphon Filter', 1999],
  ['Housemarque', 'Returnal', 2021],
  ['Team Asobi', 'Astro Bot', 2024],
  ['SIE Japan Studio', 'Astro\'s Playroom', 2020],
  ['Bluepoint Games', 'Demon\'s Souls (Remake)', 2020],
  ['Bluepoint Games', 'Shadow of the Colossus (Remake)', 2018],
  ['Bandai Namco', 'Elden Ring: Shadow of the Erdtree', 2024],
  ['thatgamecompany', 'Sky: Children of the Light', 2019],
  ['Team17', 'Worms Armageddon', 1999],
  ['Playtonic Games', 'Yooka-Laylee', 2017],
  ['Moon Studios', 'Ori and the Blind Forest', 2015],
  ['Moon Studios', 'Ori and the Will of the Wisps', 2020],
  ['Yacht Club Games', 'Shovel Knight', 2014],
  ['Thomas Happ Games', 'Axiom Verge', 2015],
  ['MercurySteam', 'Castlevania: Lords of Shadow', 2010],
  ['ArtPlay', 'Bloodstained: Ritual of the Night', 2019],
  ['Sabotage Studio', 'Sea of Stars', 2023],
  ['Sabotage Studio', 'The Messenger', 2018],
  ['Guard Crush Games', 'Streets of Rage 4', 2020],
  ['Digital Eclipse', 'The Making of Karateka', 2023],
  ['Doublefine Productions', 'Psychonauts', 2005],
  ['Doublefine Productions', 'Psychonauts 2', 2021],
  ['Doublefine Productions', 'Brütal Legend', 2009],
  ['Media Vision', 'Wild Arms', 1996],
  ['tri-Ace', 'Star Ocean: Till the End of Time', 2003],
  ['tri-Ace', 'Valkyrie Profile', 1999],
  ['From Software', 'King\'s Field', 1994],
  ['Media.Vision', 'Digimon World', 1999],
  ['Game Arts', 'Grandia', 1997],
  ['Level-5', 'Ni no Kuni: Wrath of the White Witch', 2013],
  ['Level-5', 'Professor Layton and the Curious Village', 2007],
  ['Level-5', 'Dark Cloud', 2000],
  ['Cing', 'Hotel Dusk: Room 215', 2007],
  ['Chunsoft', '999: Nine Hours, Nine Persons, Nine Doors', 2009],
  ['Spike Chunsoft', 'Danganronpa: Trigger Happy Havoc', 2010],
  ['Spike Chunsoft', 'AI: The Somnium Files', 2019],
  ['5pb.', 'Steins;Gate', 2009],
  ['ZUN', 'Touhou Project', 1996],
  ['Key', 'Clannad', 2004],
  ['Mages', 'Chaos;Head', 2008],
  ['White Wolf / Troika Games', 'Vampire: The Masquerade – Bloodlines', 2004],
  ['Silicon Knights', 'Eternal Darkness: Sanity\'s Requiem', 2002],
  ['Factor 5', 'Star Wars: Rogue Squadron II', 2001],
  ['LucasArts', 'Star Wars Jedi Knight II: Jedi Outcast', 2002],
  ['Respawn Entertainment', 'Star Wars Jedi: Fallen Order', 2019],
  ['Traveller\'s Tales', 'LEGO Star Wars: The Video Game', 2005],
  ['Rocksteady Studios', 'Batman: Arkham Knight', 2015],
  ['WB Games Montréal', 'Batman: Arkham Origins', 2013],
  ['Insomniac Games', 'Marvel\'s Spider-Man: Miles Morales', 2020],
  ['Crystal Dynamics', 'Marvel\'s Guardians of the Galaxy', 2021],
  ['Beenox', 'Spider-Man 2 (2004)', 2004],
  ['High Moon Studios', 'Transformers: War for Cybertron', 2010],
  ['Traveller\'s Tales', 'LEGO Batman: The Videogame', 2008],
  ['Telltale Games', 'The Walking Dead', 2012],
  ['Telltale Games', 'The Wolf Among Us', 2013],
  ['Telltale Games', 'Tales from the Borderlands', 2014],
  ['Dontnod Entertainment', 'Life is Strange', 2015],
  ['Quantic Dream', 'Heavy Rain', 2010],
  ['Quantic Dream', 'Detroit: Become Human', 2018],
  ['Quantic Dream', 'Beyond: Two Souls', 2013],
  ['Supermassive Games', 'Until Dawn', 2015],
  ['Night School Studio', 'Oxenfree', 2016],
  ['Cardboard Computer', 'Kentucky Route Zero', 2013],
  ['Infinite Fall', 'Night in the Woods', 2017],
  ['adult swim games', 'Death\'s Door', 2021],
  ['Bennett Foddy', 'Getting Over It with Bennett Foddy', 2017],
  ['QWOP / Bennett Foddy', 'QWOP', 2008],
  ['Foddian Games', 'Jump King', 2019],
  ['House House', 'Untitled Goose Game', 2019],
  ['Zachtronics', 'Opus Magnum', 2017],
  ['Zachtronics', 'SpaceChem', 2011],
  ['Lucas Pope', 'Papers, Please', 2013],
  ['Lucas Pope', 'Return of the Obra Dinn', 2018],
  ['11 bit studios', 'This War of Mine', 2014],
  ['11 bit studios', 'Frostpunk', 2018],
  ['Croteam', 'The Talos Principle', 2014],
  ['Demruth', 'Antichamber', 2013],
  ['2D Boy', 'World of Goo', 2008],
  ['Media Molecule', 'Tearaway', 2013],
  ['Jonatan Söderström', 'Downwell', 2015],
  ['Vlambeer', 'Nuclear Throne', 2015],
  ['Vlambeer', 'Luftrausers', 2014],
  ['Locomalito', 'Maldita Castilla', 2012],
  ['Team Meat', 'Super Meat Boy', 2010],
  ['StudioMDHR', 'Cuphead: The Delicious Last Course', 2022],
  ['Playtonic Friends', 'Pizza Tower', 2023],
  ['ConcernedApe', 'Stardew Valley 1.6', 2024],
  ['Bay 12 Games', 'Dwarf Fortress', 2006],
  ['Introversion Software', 'Uplink', 2001],
  ['Zachtronics', 'TIS-100', 2015],
];

module.exports = buildOptions(RAW_GAMES);
