const { buildOptions } = require('./build-options');

// Curated list of widely-recognized video games spanning eras, genres and platforms, used
// as the fixed option set for the "Best Video Game of All Time" poll.
// Tuples are [developer, title, year].
const RAW_GAMES = [
  ['Taito', 'Space Invaders', 1978],
  ['Namco', 'Pac-Man', 1980],
  ['Nintendo', 'Donkey Kong', 1981],
  ['Alexey Pajitnov', 'Tetris', 1984],
  ['Nintendo', 'Super Mario Bros.', 1985],
  ['Nintendo', 'The Legend of Zelda', 1986],
  ['Capcom', 'Mega Man 2', 1988],
  ['Nintendo', 'Super Mario Bros. 3', 1988],
  ['Capcom', 'Street Fighter II', 1991],
  ['Nintendo', 'Super Mario World', 1990],
  ['Nintendo', 'The Legend of Zelda: A Link to the Past', 1991],
  ['Square', 'Final Fantasy VI', 1994],
  ['Nintendo', 'Super Metroid', 1994],
  ['Square', 'Chrono Trigger', 1995],
  ['Rare', 'Donkey Kong Country', 1994],
  ['Game Freak', 'Pokémon Red and Blue', 1996],
  ['Nintendo', 'Super Mario 64', 1996],
  ['Nintendo', 'The Legend of Zelda: Ocarina of Time', 1998],
  ['Rare', 'GoldenEye 007', 1997],
  ['Square', 'Final Fantasy VII', 1997],
  ['Konami', 'Metal Gear Solid', 1998],
  ['Capcom', 'Resident Evil 2', 1998],
  ['Konami', 'Castlevania: Symphony of the Night', 1997],
  ['Naughty Dog', 'Crash Bandicoot', 1996],
  ['Insomniac Games', 'Spyro the Dragon', 1998],
  ['Valve', 'Half-Life', 1998],
  ['Blizzard Entertainment', 'StarCraft', 1998],
  ['Blizzard Entertainment', 'Diablo II', 2000],
  ['Rare', 'Banjo-Kazooie', 1998],
  ['Game Freak', 'Pokémon Gold and Silver', 1999],
  ['Nintendo', 'The Legend of Zelda: Majora’s Mask', 2000],
  ['Neversoft', 'Tony Hawk’s Pro Skater 2', 2000],
  ['Rockstar North', 'Grand Theft Auto III', 2001],
  ['Rockstar North', 'Grand Theft Auto: Vice City', 2002],
  ['Rockstar North', 'Grand Theft Auto: San Andreas', 2004],
  ['Konami', 'Metal Gear Solid 3: Snake Eater', 2004],
  ['Team Ico', 'ICO', 2001],
  ['Team Ico', 'Shadow of the Colossus', 2005],
  ['Square', 'Final Fantasy X', 2001],
  ['Square Enix', 'Kingdom Hearts', 2002],
  ['Capcom', 'Resident Evil 4', 2005],
  ['Bungie', 'Halo: Combat Evolved', 2001],
  ['Bungie', 'Halo 2', 2004],
  ['Nintendo', 'The Legend of Zelda: The Wind Waker', 2002],
  ['HAL Laboratory', 'Super Smash Bros. Melee', 2001],
  ['Retro Studios', 'Metroid Prime', 2002],
  ['Nintendo', 'Animal Crossing', 2001],
  ['Blizzard Entertainment', 'World of Warcraft', 2004],
  ['Valve', 'Half-Life 2', 2004],
  ['SCE Santa Monica Studio', 'God of War', 2005],
  ['SCE Santa Monica Studio', 'God of War II', 2007],
  ['Harmonix', 'Guitar Hero', 2005],
  ['Namco', 'Katamari Damacy', 2004],
  ['Valve', 'Portal', 2007],
  ['2K Boston', 'BioShock', 2007],
  ['Infinity Ward', 'Call of Duty 4: Modern Warfare', 2007],
  ['Infinity Ward', 'Call of Duty: Modern Warfare 2', 2009],
  ['BioWare', 'Mass Effect', 2007],
  ['BioWare', 'Mass Effect 2', 2010],
  ['Bethesda Game Studios', 'The Elder Scrolls IV: Oblivion', 2006],
  ['Bethesda Game Studios', 'The Elder Scrolls V: Skyrim', 2011],
  ['Bethesda Game Studios', 'Fallout 3', 2008],
  ['Obsidian Entertainment', 'Fallout: New Vegas', 2010],
  ['Rockstar Games', 'Red Dead Redemption', 2010],
  ['Rockstar North', 'Grand Theft Auto IV', 2008],
  ['Rockstar North', 'Grand Theft Auto V', 2013],
  ['Naughty Dog', 'Uncharted 2: Among Thieves', 2009],
  ['Naughty Dog', 'The Last of Us', 2013],
  ['Rocksteady Studios', 'Batman: Arkham Asylum', 2009],
  ['Rocksteady Studios', 'Batman: Arkham City', 2011],
  ['Nintendo', 'Super Mario Galaxy', 2007],
  ['Nintendo', 'Super Mario Galaxy 2', 2010],
  ['Nintendo', 'The Legend of Zelda: Twilight Princess', 2006],
  ['Nintendo', 'The Legend of Zelda: Skyward Sword', 2011],
  ['Number None', 'Braid', 2008],
  ['Playdead', 'Limbo', 2010],
  ['Mojang', 'Minecraft', 2011],
  ['FromSoftware', 'Demon’s Souls', 2009],
  ['FromSoftware', 'Dark Souls', 2011],
  ['Thatgamecompany', 'Journey', 2012],
  ['Valve', 'Left 4 Dead 2', 2009],
  ['Irrational Games', 'BioShock Infinite', 2013],
  ['Visceral Games', 'Dead Space', 2008],
  ['Ubisoft Montreal', 'Assassin’s Creed II', 2009],
  ['Nintendo', 'Super Smash Bros. Brawl', 2008],
  ['Nintendo', 'Wii Sports', 2006],
  ['CD Projekt Red', 'The Witcher 3: Wild Hunt', 2015],
  ['FromSoftware', 'Dark Souls III', 2016],
  ['FromSoftware', 'Bloodborne', 2015],
  ['Toby Fox', 'Undertale', 2015],
  ['Blizzard Entertainment', 'Overwatch', 2016],
  ['ConcernedApe', 'Stardew Valley', 2016],
  ['id Software', 'DOOM', 2016],
  ['Team Cherry', 'Hollow Knight', 2017],
  ['Nintendo', 'The Legend of Zelda: Breath of the Wild', 2017],
  ['Nintendo', 'Super Mario Odyssey', 2017],
  ['Atlus', 'Persona 5', 2017],
  ['Matt Makes Games', 'Celeste', 2018],
  ['Rockstar Games', 'Red Dead Redemption 2', 2018],
  ['Santa Monica Studio', 'God of War', 2018],
  ['Insomniac Games', 'Marvel’s Spider-Man', 2018],
  ['FromSoftware', 'Sekiro: Shadows Die Twice', 2019],
  ['Mobius Digital', 'Outer Wilds', 2019],
  ['ZA/UM', 'Disco Elysium', 2019],
  ['Epic Games', 'Fortnite', 2017],
  ['Respawn Entertainment', 'Apex Legends', 2019],
  ['Studio MDHR', 'Cuphead', 2017],
  ['Nintendo', 'Animal Crossing: New Horizons', 2020],
  ['Supergiant Games', 'Hades', 2020],
  ['Naughty Dog', 'The Last of Us Part II', 2020],
  ['Sucker Punch Productions', 'Ghost of Tsushima', 2020],
  ['Square Enix', 'Final Fantasy VII Remake', 2020],
  ['Hazelight Studios', 'It Takes Two', 2021],
  ['FromSoftware', 'Elden Ring', 2022],
  ['Santa Monica Studio', 'God of War Ragnarök', 2022],
  ['Guerrilla Games', 'Horizon Forbidden West', 2022],
  ['Larian Studios', 'Baldur’s Gate 3', 2023],
  ['Nintendo', 'The Legend of Zelda: Tears of the Kingdom', 2023],
  ['Insomniac Games', 'Marvel’s Spider-Man 2', 2023],
  ['Remedy Entertainment', 'Alan Wake II', 2023],
  ['Nintendo', 'Super Mario Bros. Wonder', 2023],
  ['Arrowhead Game Studios', 'Helldivers 2', 2024],
  ['Square Enix', 'Final Fantasy VII Rebirth', 2024],
];

module.exports = buildOptions(RAW_GAMES);
